from _typeshed import Incomplete
from django.views.generic.base import View
from wagtail import hooks as hooks
from wagtail.admin.forms.choosers import AnchorLinkChooserForm as AnchorLinkChooserForm, EmailLinkChooserForm as EmailLinkChooserForm, ExternalLinkChooserForm as ExternalLinkChooserForm, PhoneLinkChooserForm as PhoneLinkChooserForm
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow as render_modal_workflow
from wagtail.admin.ui.tables import Column as Column, DateColumn as DateColumn, Table as Table
from wagtail.coreutils import resolve_model_string as resolve_model_string
from wagtail.models import Locale as Locale, Page as Page, Site as Site

def shared_context(request, extra_context=None): ...
def page_models_from_string(string): ...
def can_choose_page(page, user, desired_classes, can_choose_root: bool = True, user_perm=None, target_pages=None, match_subclass: bool = True): ...

class PageChooserTable(Table):
    classname: str
    show_locale_labels: Incomplete
    def __init__(self, *args, show_locale_labels: bool = False, **kwargs) -> None: ...
    def get_context_data(self, parent_context): ...
    def get_row_classname(self, page): ...

class PageTitleColumn(Column):
    cell_template_name: str
    is_multiple_choice: Incomplete
    def __init__(self, *args, is_multiple_choice: bool = False, **kwargs) -> None: ...
    def get_value(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class ParentPageColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class PageStatusColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class PageNavigateToChildrenColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class PageCheckboxSelectColumn(Column):
    cell_template_name: str

class BrowseView(View):
    @property
    def columns(self): ...
    def get_object_list(self): ...
    def filter_object_list(self, pages): ...
    i18n_enabled: Incomplete
    is_multiple_choice: Incomplete
    desired_classes: Incomplete
    parent_page: Incomplete
    def get(self, request, parent_page_id=None): ...

class SearchView(View):
    @property
    def columns(self): ...
    i18n_enabled: Incomplete
    is_multiple_choice: Incomplete
    def get(self, request): ...

class ChosenMultipleView(View):
    def render_chosen_response(self, result): ...
    def get(self, request): ...

class BaseLinkFormView(View):
    def get_initial_data(self): ...
    def get_url_from_field_value(self, value): ...
    def get_result_data(self): ...
    form: Incomplete
    def get(self, request): ...
    def post(self, request): ...
    def render_form_response(self): ...
    def render_chosen_response(self, result): ...

LINK_CONVERSION_ALL: str
LINK_CONVERSION_EXACT: str
LINK_CONVERSION_CONFIRM: str

class ExternalLinkView(BaseLinkFormView):
    form_prefix: str
    form_class = ExternalLinkChooserForm
    template_name: str
    step_name: str
    link_url_field_name: str
    form: Incomplete
    def post(self, request): ...

class AnchorLinkView(BaseLinkFormView):
    form_prefix: str
    form_class = AnchorLinkChooserForm
    template_name: str
    step_name: str
    link_url_field_name: str
    def get_url_from_field_value(self, value): ...

class EmailLinkView(BaseLinkFormView):
    form_prefix: str
    form_class = EmailLinkChooserForm
    template_name: str
    step_name: str
    link_url_field_name: str
    def get_initial_data(self): ...
    def get_url_from_field_value(self, value): ...
    def get_result_data(self): ...
    form: Incomplete
    def post(self, request): ...
    def parse_email_link(self, mailto): ...

class PhoneLinkView(BaseLinkFormView):
    form_prefix: str
    form_class = PhoneLinkChooserForm
    template_name: str
    step_name: str
    link_url_field_name: str
    def get_url_from_field_value(self, value): ...
