from _typeshed import Incomplete
from collections.abc import Generator
from django.utils.dateformat import Formatter
from django.utils.functional import cached_property as cached_property
from wagtail.admin.widgets.button import Button as Button
from wagtail.coreutils import multigetattr as multigetattr

class Echo:
    def write(self, value): ...

def list_to_str(value): ...

class ExcelDateFormatter(Formatter):
    data: Incomplete
    def get(self): ...
    def __getattr__(self, name): ...

class SpreadsheetExportMixin:
    FORMAT_XLSX: str
    FORMAT_CSV: str
    FORMATS: Incomplete
    list_export: Incomplete
    custom_field_preprocess: Incomplete
    custom_value_preprocess: Incomplete
    export_headings: Incomplete
    export_buttons_template_name: str
    export_filename: str
    is_export: Incomplete
    def setup(self, request, *args, **kwargs) -> None: ...
    def get_paginate_by(self, queryset): ...
    def get_filename(self): ...
    def to_row_dict(self, item): ...
    def get_preprocess_function(self, field, value, export_format): ...
    def preprocess_field_value(self, field, value, export_format): ...
    def generate_xlsx_row(self, worksheet, row_dict, date_format=None) -> Generator[Incomplete]: ...
    def write_csv_row(self, writer, row_dict): ...
    def get_heading(self, queryset, field): ...
    def stream_csv(self, queryset) -> Generator[Incomplete]: ...
    def write_xlsx(self, queryset, output) -> None: ...
    def write_xlsx_response(self, queryset): ...
    def write_csv_response(self, queryset): ...
    def as_spreadsheet(self, queryset, spreadsheet_format): ...
    def get_export_url(self, format): ...
    @property
    def xlsx_export_url(self): ...
    @property
    def csv_export_url(self): ...
    @cached_property
    def show_export_buttons(self): ...
    @cached_property
    def header_more_buttons(self): ...
