from wagtail.models.reference_index import ReferenceIndex as ReferenceIndex

class ReferenceIndexMixin:
    object_references: dict
    is_protected: bool
    def annotate_items(self, items): ...
    def get_context_data(self, **kwargs): ...
    def get_usage_url(self, item) -> None: ...
    def object_context(self, item): ...
    def prepare_action(self, objects, objects_without_access) -> None: ...
