from collections.abc import Sequence
from typing import Any

from .base import Panel

class PanelGroup(Panel):
    children: Sequence[Panel]
    permission: str | None
    def __init__(self, children: Sequence[Panel] = (), *args: Any, permission: str | None = None, **kwargs: Any) -> None: ...
    def clone_kwargs(self) -> dict[str, Any]: ...
    def get_form_options(self) -> dict[str, Any]: ...
    def on_model_bound(self) -> None: ...

class TabbedInterface(PanelGroup):
    def __init__(self, *args: Any, show_comments_toggle: bool = True, **kwargs: Any) -> None: ...

class ObjectList(PanelGroup): ...

class FieldRowPanel(PanelGroup): ...

class MultiFieldPanel(PanelGroup): ...
