from django.urls import URLPattern

from wagtail.admin.viewsets.base import ViewSet, ViewSetGroup as ViewSetGroup

class ViewSetRegistry:
    viewsets: list[ViewSet]
    def __init__(self) -> None: ...
    def populate(self) -> None: ...
    def register(self, viewset: ViewSet | ViewSetGroup) -> ViewSet | None: ...
    def get_urlpatterns(self) -> list[URLPattern]: ...

viewsets: ViewSetRegistry
