from _typeshed import Incomplete
from wagtail import hooks as hooks
from wagtail.admin.viewsets.base import ViewSetGroup as ViewSetGroup

class ViewSetRegistry:
    viewsets: Incomplete
    def __init__(self) -> None: ...
    def populate(self) -> None: ...
    def register(self, viewset): ...
    def get_urlpatterns(self): ...

viewsets: Incomplete
