from typing import Any

from django import forms
from django.core import checks
from django.core.exceptions import ValidationError
from django.utils.functional import cached_property

__all__ = [
    "BaseBlock",
    "Block",
    "BoundBlock",
    "DeclarativeSubBlocksMetaclass",
    "BlockWidget",
    "BlockField",
]

def get_error_json_data(error: ValidationError) -> dict[str, Any]: ...
def get_error_list_json_data(errors: Any) -> list[dict[str, Any]]: ...
def get_help_icon() -> str: ...

class BaseBlock(type):
    def __new__(mcs, name: str, bases: tuple[type, ...], attrs: dict[str, Any]) -> BaseBlock: ...

class Block(metaclass=BaseBlock):
    name: str
    creation_counter: int
    definition_registry: dict[str, Block]
    TEMPLATE_VAR: str
    DEFAULT_PREVIEW_TEMPLATE: str
    MUTABLE_META_ATTRIBUTES: list[str]
    label: str
    meta: Any

    class Meta:
        label: str | None
        icon: str
        classname: str | None
        form_attrs: dict[str, str] | None
        group: str
        default: Any
        template: str | None

    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def construct_from_lookup(cls, lookup: Any, *args: Any, **kwargs: Any) -> Block: ...
    def set_name(self, name: str) -> None: ...
    def set_meta_options(self, opts: dict[str, Any]) -> None: ...
    def value_from_datadict(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> Any: ...
    def value_omitted_from_data(self, data: dict[str, Any], files: dict[str, Any], name: str) -> bool: ...
    def bind(self, value: Any, prefix: str | None = None, errors: Any | None = None) -> BoundBlock: ...
    def get_default(self) -> Any: ...
    def clean(self, value: Any) -> Any: ...
    def normalize(self, value: Any) -> Any: ...
    def to_python(self, value: Any) -> Any: ...
    def bulk_to_python(self, values: list[Any]) -> list[Any]: ...
    def get_prep_value(self, value: Any) -> Any: ...
    def get_form_state(self, value: Any) -> Any: ...
    def get_context(self, value: Any, parent_context: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def get_template(self, value: Any | None = None, context: dict[str, Any] | None = None) -> str | None: ...
    def render(self, value: Any, context: dict[str, Any] | None = None) -> str: ...
    def get_preview_context(self, value: Any, parent_context: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def get_preview_template(self, value: Any | None = None, context: dict[str, Any] | None = None) -> str: ...
    def get_preview_value(self) -> Any: ...
    @cached_property
    def is_previewable(self) -> bool: ...
    def get_description(self) -> str: ...
    def get_api_representation(self, value: Any, context: dict[str, Any] | None = None) -> Any: ...
    def render_basic(self, value: Any, context: dict[str, Any] | None = None) -> str: ...
    def get_searchable_content(self, value: Any) -> list[str]: ...
    def extract_references(self, value: Any) -> list[Any]: ...
    def get_block_by_content_path(self, value: Any, path_elements: list[str]) -> BoundBlock | None: ...
    def check(self, **kwargs: Any) -> list[checks.Error]: ...
    def id_for_label(self, prefix: str) -> str | None: ...
    @property
    def required(self) -> bool: ...
    @cached_property
    def canonical_module_path(self) -> str: ...
    def deconstruct(self) -> tuple[str, list[Any], dict[str, Any]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BoundBlock:
    block: Block
    value: Any
    prefix: str
    errors: Any
    def __init__(self, block: Block, value: Any, prefix: str | None = None, errors: Any | None = None) -> None: ...
    def render(self, context: dict[str, Any] | None = None) -> str: ...
    def render_as_block(self, context: dict[str, Any] | None = None) -> str: ...
    @property
    def id_for_label(self) -> str | None: ...
    def __str__(self) -> str: ...

class DeclarativeSubBlocksMetaclass(BaseBlock):
    def __new__(mcs, name: str, bases: tuple[type, ...], attrs: dict[str, Any]) -> DeclarativeSubBlocksMetaclass: ...

class BlockWidget(forms.Widget):
    block_def: Block
    def __init__(self, block_def: Block, attrs: dict[str, Any] | None = None) -> None: ...
    def render_with_errors(self, name: str, value: Any, attrs: dict[str, Any] | None = None, errors: Any | None = None) -> str: ...

class BlockField(forms.Field):
    block: Block
    def __init__(self, block: Block | None = None, **kwargs: Any) -> None: ...
