from typing import Any

from wagtail.blocks.base import Block

class BlockDefinitionLookup:
    def __init__(self, lookup_list: list[Any]) -> None: ...
    def get_block(self, index: int) -> Block: ...

class BlockDefinitionLookupBuilder:
    def add_block(self, block: Block) -> int: ...
    def get_lookup_as_dict(self) -> dict[str, Any]: ...
