from collections.abc import Iterator, MutableSequence
from typing import Any

from django.core.exceptions import ValidationError
from django.utils.functional import cached_property

from .base import Block, BoundBlock

__all__ = ["ListBlock", "ListBlockValidationError"]

class ListBlockValidationError(ValidationError):
    non_block_errors: Any
    block_errors: list[ValidationError | None]
    def __init__(self, block_errors: list[ValidationError | None] | None = None, non_block_errors: Any | None = None) -> None: ...
    def as_json_data(self) -> dict[str, Any]: ...

class ListValue(MutableSequence[Any]):
    bound_blocks: list[BoundBlock]
    def __init__(self, block: Block, values: list[Any] | None = None, bound_blocks: list[BoundBlock] | None = None) -> None: ...
    def __getitem__(self, i: int) -> Any: ...  # type: ignore[override]
    def __setitem__(self, i: int, item: Any) -> None: ...  # type: ignore[override]
    def __delitem__(self, i: int) -> None: ...  # type: ignore[override]
    def __len__(self) -> int: ...
    def insert(self, index: int, value: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __html__(self) -> str: ...
    def render_as_block(self, context: dict[str, Any] | None = None) -> str: ...

class ListBlock(Block):
    child_block: Block
    def __init__(self, child_block: Block | type[Block], search_index: bool = True, min_num: int | None = None, max_num: int | None = None, **kwargs: Any) -> None: ...
    def get_default(self) -> ListValue: ...
    def value_from_datadict(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> ListValue: ...
    def value_omitted_from_data(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> bool: ...
    def clean(self, value: Any) -> ListValue: ...
    def to_python(self, value: Any) -> ListValue: ...
    def bulk_to_python(self, values: list[Any]) -> list[ListValue]: ...
    def get_prep_value(self, value: Any) -> list[Any]: ...
    def normalize(self, value: Any) -> ListValue: ...
    def get_form_state(self, value: Any) -> list[dict[str, Any]]: ...
    def get_searchable_content(self, value: Any) -> list[str]: ...
    def extract_references(self, value: Any) -> Any: ...
    def get_block_by_content_path(self, value: Any, path_elements: list[str]) -> BoundBlock | None: ...
