from typing import Any

from .base import Block

__all__ = ["StaticBlock"]

class StaticBlock(Block):
    def __init__(self, **kwargs: Any) -> None: ...
    def value_from_datadict(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> None: ...
    def value_omitted_from_data(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> bool: ...
    def clean(self, value: Any) -> None: ...
    def to_python(self, value: Any) -> None: ...
    def get_prep_value(self, value: Any) -> None: ...
    def render_basic(self, value: Any, context: dict[str, Any] | None = None) -> str: ...
