import collections
import uuid
from collections.abc import Iterator, MutableSequence
from typing import Any

from django.core.exceptions import ValidationError
from django.utils.functional import cached_property

from .base import Block, BoundBlock, DeclarativeSubBlocksMetaclass

__all__ = [
    "BaseStreamBlock",
    "StreamBlock",
    "StreamValue",
    "StreamBlockValidationError",
]

class StreamBlockValidationError(ValidationError):
    non_block_errors: Any
    block_errors: dict[int, ValidationError]
    def __init__(self, block_errors: dict[int, ValidationError] | None = None, non_block_errors: Any | None = None) -> None: ...
    def as_json_data(self) -> dict[str, Any]: ...

class BaseStreamBlock(Block):
    MUTABLE_META_ATTRIBUTES: list[str]
    child_blocks: collections.OrderedDict[str, Block]

    class Meta:
        min_num: int | None
        max_num: int | None
        block_counts: dict[str, dict[str, int]] | None
        collapsed: bool
        required: bool

    def __init__(self, local_blocks: list[tuple[str, Block]] | None = None, search_index: bool = True, **kwargs: Any) -> None: ...
    def get_default(self) -> StreamValue: ...
    def sorted_child_blocks(self) -> list[Block]: ...
    def grouped_child_blocks(self) -> collections.OrderedDict[str, list[Block]]: ...
    def value_from_datadict(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> StreamValue: ...
    def value_omitted_from_data(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> bool: ...
    def clean(self, value: Any) -> StreamValue: ...
    def to_python(self, value: Any) -> StreamValue: ...
    def bulk_to_python(self, values: list[Any]) -> list[StreamValue]: ...
    def get_prep_value(self, value: Any) -> list[dict[str, Any]]: ...
    def normalize(self, value: Any) -> StreamValue: ...
    def get_form_state(self, value: Any) -> list[dict[str, Any]]: ...
    def get_searchable_content(self, value: Any) -> list[str]: ...
    def extract_references(self, value: Any) -> Any: ...
    def get_block_by_content_path(self, value: Any, path_elements: list[str]) -> BoundBlock | None: ...

class StreamBlock(BaseStreamBlock, metaclass=DeclarativeSubBlocksMetaclass):
    base_blocks: collections.OrderedDict[str, Block]

class StreamValue(MutableSequence[StreamValue.StreamChild]):
    stream_block: Block
    is_lazy: bool
    raw_text: str | None

    class StreamChild(BoundBlock):
        id: str
        block_type: str
        def __init__(self, block: Block, value: Any, id: str = ..., block_type: str = ...) -> None: ...

    def __init__(self, stream_block: Block, stream_data: list[Any] | None = None, is_lazy: bool = False, raw_text: str | None = None) -> None: ...
    def __getitem__(self, i: int) -> StreamValue.StreamChild: ...  # type: ignore[override]
    def __setitem__(self, i: int, item: Any) -> None: ...  # type: ignore[override]
    def __delitem__(self, i: int) -> None: ...  # type: ignore[override]
    def __len__(self) -> int: ...
    def insert(self, index: int, value: Any) -> None: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __html__(self) -> str: ...
    def render_as_block(self, context: dict[str, Any] | None = None) -> str: ...
    def __iter__(self) -> Iterator[StreamValue.StreamChild]: ...
