import collections
from typing import Any

from django.core.exceptions import ValidationError
from django.utils.functional import cached_property

from .base import Block, BoundBlock, DeclarativeSubBlocksMetaclass

__all__ = [
    "BlockGroup",
    "BaseStructBlock",
    "StructBlock",
    "StructValue",
    "StructBlockValidationError",
]

class StructBlockValidationError(ValidationError):
    non_block_errors: Any
    block_errors: dict[str, ValidationError]
    def __init__(self, block_errors: dict[str, ValidationError] | None = None, non_block_errors: Any | None = None) -> None: ...
    def as_json_data(self) -> dict[str, Any]: ...

class BlockGroup:
    children: list[str | BlockGroup]
    settings: list[str | BlockGroup]
    heading: str
    clean_name: str
    classname: str
    help_text: str
    icon: str
    attrs: dict[str, Any]
    label_format: str | None
    def __init__(
        self,
        children: list[str | BlockGroup],
        settings: list[str | BlockGroup] | None = None,
        heading: str = "",
        classname: str = "",
        help_text: str = "",
        icon: str = "placeholder",
        attrs: dict[str, Any] | None = None,
        label_format: str | None = None,
    ) -> None: ...
    @cached_property
    def unique_children_and_settings(self) -> tuple[list[tuple[str | BlockGroup, str]], list[tuple[str | BlockGroup, str]]]: ...
    def get_sorted_block_names(self) -> list[str]: ...

class StructValue(collections.OrderedDict[str, Any]):
    block: Block
    def __init__(self, block: Block, *args: Any) -> None: ...
    def __html__(self) -> str: ...
    def render_as_block(self, context: dict[str, Any] | None = None) -> str: ...
    @cached_property
    def bound_blocks(self) -> collections.OrderedDict[str, BoundBlock]: ...

class BaseStructBlock(Block):
    search_index: bool
    child_blocks: collections.OrderedDict[str, Block]
    def __init__(self, local_blocks: list[tuple[str, Block]] | None = None, search_index: bool = True, **kwargs: Any) -> None: ...
    def get_default(self) -> StructValue: ...
    def value_from_datadict(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> StructValue: ...
    def value_omitted_from_data(self, data: dict[str, Any], files: dict[str, Any], prefix: str) -> bool: ...
    def clean(self, value: Any) -> StructValue: ...
    def to_python(self, value: Any) -> StructValue: ...
    def bulk_to_python(self, values: list[Any]) -> list[StructValue]: ...
    def get_prep_value(self, value: Any) -> dict[str, Any]: ...
    def normalize(self, value: Any) -> StructValue: ...
    def get_form_state(self, value: Any) -> dict[str, Any]: ...
    def get_form_context(self, value: Any, prefix: str = "", errors: Any | None = None) -> dict[str, Any]: ...
    def get_searchable_content(self, value: Any) -> list[str]: ...
    def extract_references(self, value: Any) -> Any: ...
    def get_block_by_content_path(self, value: Any, path_elements: list[str]) -> BoundBlock | None: ...
    def get_form_layout(self) -> BlockGroup: ...

class StructBlock(BaseStructBlock, metaclass=DeclarativeSubBlocksMetaclass):
    base_blocks: collections.OrderedDict[str, Block]
