from _typeshed import Incomplete
from django import template
from wagtail import VERSION as VERSION, __version__ as __version__
from wagtail.models import Page as Page, Site as Site
from wagtail.rich_text import RichText as RichText, expand_db_html as expand_db_html
from wagtail.utils.version import get_main_version as get_main_version

register: Incomplete

def pageurl(context, page, fallback=None): ...
def fullpageurl(context, page, fallback=None): ...
def slugurl(context, slug): ...
@register.simple_tag
def wagtail_version(): ...
@register.simple_tag
def wagtail_documentation_path(): ...
@register.simple_tag
def wagtail_release_notes_path(): ...
@register.simple_tag
def wagtail_feature_release_whats_new_link(): ...
@register.simple_tag
def wagtail_feature_release_editor_guide_link(): ...
@register.filter
def richtext(value): ...

class IncludeBlockNode(template.Node):
    block_var: Incomplete
    extra_context: Incomplete
    use_parent_context: Incomplete
    def __init__(self, block_var, extra_context, use_parent_context) -> None: ...
    def render(self, context): ...

@register.tag
def include_block(parser, token): ...
def wagtail_site(context): ...
