[tox]
isolated_build = True
envlist = stubtest,mypy-plugins

[testenv]
runner = uv-venv-lock-runner
package = wheel
dependency_groups = dev

[testenv:stubtest]
commands =
    python {toxinidir}/run_stubtest.py

[testenv:mypy-plugins]
commands =
    pytest tests/ {posargs}
