class MenuItem:
    label: str
    url: str
    icon_name: str
    priority: int
    def __init__(self, label: str, url: str, icon_name: str = "", priority: int = 1000) -> None: ...
    def is_shown(self, user): ...
    def __lt__(self, other): ...
