from _typeshed import Incomplete

register: Incomplete

def cell_classname(context, row_index, col_index, table_header=None): ...
def cell_hidden(context, row_index, col_index, table_header=None): ...
def cell_span(context, row_index, col_index, table_header=None): ...
