from collections.abc import Generator
from types import ModuleType

def get_app_modules() -> Generator[tuple[str, ModuleType]]: ...
def get_app_submodules(submodule_name: str) -> Generator[tuple[str, ModuleType]]: ...
