from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property

class cached_classmethod(dict):
    fn: Incomplete
    def __init__(self, fn) -> None: ...
    def __get__(self, instance, owner): ...
    def __missing__(self, cls): ...

class _cache:
    cache: Incomplete
    cls: Incomplete
    fn: Incomplete
    def __init__(self, cache, cls, fn) -> None: ...
    @cached_property
    def value(self): ...
    def __call__(self): ...
    def cache_clear(self) -> None: ...

def xframe_options_sameorigin_override(view_func): ...
