from _typeshed import Incomplete
from wagtail.coreutils import resolve_model_string as resolve_model_string

class ObjectTypeRegistry:
    values_by_exact_class: Incomplete
    values_by_class: Incomplete
    def __init__(self) -> None: ...
    def register(self, cls, value=None, exact_class: bool = False) -> None: ...
    def get_by_type(self, cls): ...
    def get(self, obj): ...

class ModelFieldRegistry(ObjectTypeRegistry):
    values_by_fk_related_model: Incomplete
    def __init__(self) -> None: ...
    def register(self, field_class, to=None, value=None, exact_class: bool = False) -> None: ...
    def foreign_key_lookup(self, field): ...
