from django.http import FileResponse, HttpRequest, HttpResponseNotModified

def sendfile(request: HttpRequest, filename: str, **kwargs: object) -> FileResponse | HttpResponseNotModified: ...
def was_modified_since(header: str | None = None, mtime: float = 0) -> bool: ...
