import datetime

def ensure_utc(value: datetime.datetime) -> datetime.datetime: ...
def parse_datetime_localized(date_string: str) -> datetime.datetime | None: ...
def render_timestamp(timestamp: datetime.datetime) -> str: ...
