from collections.abc import Mapping
from typing import Any

def deep_update(source: dict[str, Any], overrides: Mapping[str, Any]) -> dict[str, Any]: ...
def flatten_choices(choices: list[Any] | dict[str, Any]) -> dict[str, Any]: ...
