def get_version(version: tuple[int, int, int, str, int]) -> str: ...
def get_main_version(version: tuple[int, int, int, str, int] | None = None, include_patch: bool = True) -> str: ...
def get_complete_version(version: tuple[int, int, int, str, int] | None = None) -> tuple[int, int, int, str, int]: ...
def get_semver_version(version: tuple[int, int, int, str, int]) -> str: ...
