from collections import OrderedDict
from collections.abc import Sequence
from typing import Any

from wagtail.admin.forms import WagtailAdminPageForm as WagtailAdminPageForm
from wagtail.compat import URLField as URLField
from wagtail.contrib.forms.models import AbstractFormField
import django.forms

class BaseForm(django.forms.Form):
    user: Any
    page: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class FormBuilder:
    fields: Sequence[AbstractFormField]
    def __init__(self, fields: Sequence[AbstractFormField]) -> None: ...
    def create_singleline_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.CharField: ...
    def create_multiline_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.CharField: ...
    def create_date_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.DateField: ...
    def create_datetime_field(
        self, field: AbstractFormField, options: dict[str, Any]
    ) -> django.forms.DateTimeField: ...
    def create_email_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.EmailField: ...
    def create_url_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.URLField: ...
    def create_number_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.DecimalField: ...
    def create_dropdown_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.ChoiceField: ...
    def create_multiselect_field(
        self, field: AbstractFormField, options: dict[str, Any]
    ) -> django.forms.MultipleChoiceField: ...
    def create_radio_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.ChoiceField: ...
    def create_checkboxes_field(
        self, field: AbstractFormField, options: dict[str, Any]
    ) -> django.forms.MultipleChoiceField: ...
    def create_checkbox_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.BooleanField: ...
    def create_hidden_field(self, field: AbstractFormField, options: dict[str, Any]) -> django.forms.CharField: ...
    def get_create_field_function(self, type: str) -> Any: ...
    def get_formatted_field_choices(self, field: AbstractFormField) -> list[tuple[str, str]]: ...
    def get_formatted_field_initial(self, field: AbstractFormField) -> list[str]: ...
    @property
    def formfields(self) -> OrderedDict[str, django.forms.Field]: ...
    def get_field_options(self, field: AbstractFormField) -> dict[str, Any]: ...
    def get_form_class(self) -> type[BaseForm]: ...

class SelectDateForm(django.forms.Form):
    date_from: django.forms.DateField
    date_to: django.forms.DateField

class WagtailAdminFormPageForm(WagtailAdminPageForm):
    def clean(self): ...
