from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property
from wagtail.admin.panels import Panel as Panel

class FormSubmissionsPanel(Panel):
    heading: Incomplete
    def on_model_bound(self) -> None: ...
    class BoundPanel(Panel.BoundPanel):
        template_name: str
        @cached_property
        def submissions(self): ...
        @cached_property
        def submission_count(self): ...
        def is_shown(self): ...
        def get_context_data(self, parent_context=None): ...
