from typing import Any

from django.db.models.expressions import Expression, Value

class LexemeCombinable(Expression):
    BITAND: str
    BITOR: str
    def bitand(self, other: LexemeCombinable) -> CombinedLexeme: ...
    def bitor(self, other: LexemeCombinable) -> CombinedLexeme: ...
    def __or__(self, other: LexemeCombinable) -> CombinedLexeme: ...
    def __and__(self, other: LexemeCombinable) -> CombinedLexeme: ...

class Lexeme(LexemeCombinable, Value):
    def __init__(self, value: str, output_field: Any = None, *, invert: bool = False, prefix: bool = False, weight: str | None = None) -> None: ...
    def as_sql(self, compiler: Any, connection: Any) -> tuple[str, list[Any]]: ...

class CombinedLexeme(LexemeCombinable):
    def __init__(self, lhs: LexemeCombinable, connector: str, rhs: LexemeCombinable, output_field: Any = None) -> None: ...
    def as_sql(self, compiler: Any, connection: Any) -> tuple[str, list[Any]]: ...
