WEIGHTS: str
WEIGHTS_COUNT: int
BOOSTS_WEIGHTS: list[tuple[float, str]]
WEIGHTS_VALUES: list[float]

def get_boosts() -> set[float]: ...
def determine_boosts_weights(boosts: tuple[float, ...] = ...) -> list[tuple[float, str]]: ...
def set_weights() -> None: ...
def get_weight(boost: float) -> str: ...
def get_sql_weights() -> str: ...
