from typing import Any

from django.db.models import QuerySet

from wagtail.search.backends.base import BaseSearchBackend, BaseSearchQueryCompiler, BaseSearchResults
from wagtail.search.index import AutocompleteField, SearchField

class ObjectIndexer:
    obj: Any
    backend: SQLiteSearchBackend
    def __init__(self, obj: Any, backend: SQLiteSearchBackend) -> None: ...
    def prepare_value(self, value: Any) -> str: ...
    def prepare_field(self, obj: Any, field: Any) -> list[tuple[str, str, str]]: ...
    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def body(self) -> str: ...
    @property
    def autocomplete(self) -> str: ...
    def as_vector(self, texts: list[tuple[str, str, str]], for_autocomplete: bool = False) -> Any: ...

class Index:
    backend: SQLiteSearchBackend
    def __init__(self, backend: SQLiteSearchBackend) -> None: ...
    def add_model(self, model: type) -> None: ...
    def refresh(self) -> None: ...
    def delete_stale_model_entries(self, model: type) -> None: ...
    def delete_stale_entries(self) -> None: ...
    def add_item(self, obj: Any) -> None: ...
    def add_items(self, model: type, objs: Any) -> None: ...
    def delete_item(self, item: Any) -> None: ...
    def __str__(self) -> str: ...

class SQLiteSearchRebuilder:
    index: Index
    def __init__(self, index: Index) -> None: ...
    def start(self) -> Index: ...
    def finish(self) -> None: ...

class SQLiteSearchAtomicRebuilder(SQLiteSearchRebuilder):
    def __init__(self, index: Index) -> None: ...
    def start(self) -> Index: ...
    def finish(self) -> None: ...

class SQLiteSearchQueryCompiler(BaseSearchQueryCompiler):
    DEFAULT_OPERATOR: str
    LAST_TERM_IS_PREFIX: bool
    TARGET_SEARCH_FIELD_TYPE: type[SearchField]
    FTS_TABLE_FIELDS: list[str]

class SQLiteAutocompleteQueryCompiler(SQLiteSearchQueryCompiler):
    LAST_TERM_IS_PREFIX: bool
    TARGET_SEARCH_FIELD_TYPE: type[AutocompleteField]
    FTS_TABLE_FIELDS: list[str]

class SQLiteSearchResults(BaseSearchResults):
    supports_facet: bool
    def get_queryset(self, for_count: bool = False) -> QuerySet[Any]: ...
    def facet(self, field_name: str) -> dict[Any, int]: ...

class SQLiteSearchBackend(BaseSearchBackend):
    query_compiler_class: type[SQLiteSearchQueryCompiler]
    autocomplete_query_compiler_class: type[SQLiteAutocompleteQueryCompiler]
    results_class: type[SQLiteSearchResults]
    rebuilder_class: type[SQLiteSearchRebuilder]
    atomic_rebuilder_class: type[SQLiteSearchAtomicRebuilder]
    def __init__(self, params: dict[str, Any]) -> None: ...
    def get_index_for_model(self, model: type) -> Index: ...
    def get_index_for_object(self, obj: Any) -> Index: ...
    def reset_index(self) -> None: ...
    def add_type(self, model: type) -> None: ...
    def refresh_index(self) -> None: ...
    def add(self, obj: Any) -> None: ...
    def add_bulk(self, model: type, obj_list: Any) -> None: ...
    def delete(self, obj: Any) -> None: ...

SearchBackend = SQLiteSearchBackend
