from _typeshed import Incomplete

class Dataset(list):
    headers: Incomplete
    def __init__(self, rows=(), headers=None) -> None: ...

class CSV:
    def is_binary(self): ...
    def get_read_mode(self): ...
    def create_dataset(self, data, delimiter: str = ","): ...

class TSV(CSV):
    def create_dataset(self, data): ...

class XLSX:
    def is_binary(self): ...
    def get_read_mode(self): ...
    def create_dataset(self, data): ...

DEFAULT_FORMATS: Incomplete
