from typing import Any

from django.db import migrations

def add_image_permissions_to_admin_groups(apps, schema_editor) -> None: ...
def remove_image_permissions(apps, schema_editor) -> None: ...
def get_image_permissions(apps): ...
def copy_image_permissions_to_collections(apps, schema_editor) -> None: ...
def remove_image_permissions_from_collections(apps, schema_editor) -> None: ...

class Migration(migrations.Migration):
    replaces: list[tuple[str, str]]
    dependencies: list[tuple[str, str]]
    operations: list[Any]
