from _typeshed import Incomplete
from django.db import migrations

def add_image_permissions_to_admin_groups(apps, schema_editor) -> None: ...
def remove_image_permissions(apps, schema_editor) -> None: ...
def get_image_permissions(apps): ...
def copy_image_permissions_to_collections(apps, schema_editor) -> None: ...
def remove_image_permissions_from_collections(apps, schema_editor) -> None: ...

class Migration(migrations.Migration):
    replaces: Incomplete
    dependencies: Incomplete
    operations: Incomplete
