from .base import EmbedFinder as EmbedFinder
from _typeshed import Incomplete
from wagtail.embeds.exceptions import EmbedException as EmbedException, EmbedNotFoundException as EmbedNotFoundException

class EmbedlyException(EmbedException): ...
class AccessDeniedEmbedlyException(EmbedlyException): ...

class EmbedlyFinder(EmbedFinder):
    key: Incomplete
    def __init__(self, key=None) -> None: ...
    def get_key(self): ...
    def accept(self, url): ...
    def find_embed(self, url, max_width=None, key=None): ...
embed_finder_class = EmbedlyFinder
