from _typeshed import Incomplete
from django.db import migrations

logger: Incomplete

def legacy_to_iso_format(date_string, tz=None): ...
def iso_to_legacy_format(date_string, tz=None): ...
def migrate_logs_with_created_only(model, converter) -> None: ...
def migrate_schedule_logs(model, converter) -> None: ...
def migrate_custom_to_iso_format(apps, schema_editor) -> None: ...
def migrate_iso_to_custom_format(apps, schema_editor) -> None: ...

class Migration(migrations.Migration):
    dependencies: Incomplete
    operations: Incomplete
