from _typeshed import Incomplete
from wagtail.contrib.settings.models import BaseGenericSetting as BaseGenericSetting
from wagtail.contrib.settings.models import BaseSiteSetting as BaseSiteSetting
from wagtail.models.sites import Site as Site

from .registry import registry as registry

class SettingProxy(dict):
    request_or_site: Incomplete
    def __init__(self, request_or_site) -> None: ...
    def __missing__(self, app_label): ...

class SettingModuleProxy(dict):
    app_label: Incomplete
    request_or_site: Incomplete
    def __init__(self, request_or_site, app_label) -> None: ...
    def __getitem__(self, model_name): ...
    def __missing__(self, model_name): ...
    def get_setting(self, model_name): ...

def settings(request): ...
