from .forms import SiteSwitchForm as SiteSwitchForm
from .models import BaseGenericSetting as BaseGenericSetting, BaseSiteSetting as BaseSiteSetting
from .registry import registry as registry
from _typeshed import Incomplete
from wagtail.admin import messages as messages
from wagtail.admin.panels import ObjectList as ObjectList, extract_panel_definitions_from_model_class as extract_panel_definitions_from_model_class
from wagtail.admin.ui.side_panels import ChecksSidePanel as ChecksSidePanel, PreviewSidePanel as PreviewSidePanel
from wagtail.admin.views import generic as generic
from wagtail.admin.views.generic import preview as preview
from wagtail.models import PreviewableMixin as PreviewableMixin, Site as Site

def get_model_from_url_params(app_name, model_name): ...
def get_setting_edit_handler(model): ...
def redirect_to_relevant_instance(request, app_name, model_name): ...

class EditView(generic.EditView):
    template_name: str
    edit_url_name: str
    preview_url_name: str
    error_message: Incomplete
    permission_required: str
    app_name: Incomplete
    model_name: Incomplete
    model: Incomplete
    permission_policy: Incomplete
    pk: Incomplete
    object: Incomplete
    def setup(self, request, app_name, model_name, *args, **kwargs) -> None: ...
    def run_before_hook(self): ...
    def run_after_hook(self): ...
    def get_header_icon(self): ...
    site: Incomplete
    def get_object(self, queryset=None): ...
    def get_panel(self): ...
    def get_edit_url(self): ...
    def get_success_buttons(self) -> None: ...
    def get_page_subtitle(self): ...
    def get_context_data(self, **kwargs): ...
    def get_success_url(self): ...
    def get_success_message(self): ...
    def get_preview_url(self): ...
    def get_side_panels(self): ...

class PreviewOnEdit(preview.PreviewOnEdit):
    app_name: Incomplete
    model_name: Incomplete
    model: Incomplete
    permission_policy: Incomplete
    pk: Incomplete
    def setup(self, request, app_name, model_name, *args, **kwargs) -> None: ...
    site: Incomplete
    def get_object(self, queryset=None): ...
    def get_extra_request_attrs(self): ...
