from wagtail.admin.widgets.auto_height_text import *  # noqa: F403
from wagtail.admin.widgets.boolean_radio_select import *  # noqa: F403
from wagtail.admin.widgets.button import *  # noqa: F403
from wagtail.admin.widgets.chooser import *  # noqa: F403
from wagtail.admin.widgets.datetime import *  # noqa: F403
from wagtail.admin.widgets.filtered_select import *  # noqa: F403
from wagtail.admin.widgets.slug import *  # noqa: F403
from wagtail.admin.widgets.switch import *  # noqa: F403
from wagtail.admin.widgets.tags import *  # noqa: F403
