from typing import Any

from wagtail.admin.ui.components import Component

class BaseButton(Component):
    label: str
    url: str | None
    classname: str
    icon_name: str
    attrs: dict[str, Any]
    priority: int
    show: bool
    def __init__(self, label: str = "", url: str | None = None, classname: str = "", icon_name: str = "", attrs: dict[str, Any] | None = None, priority: int = 1000, show: bool = True) -> None: ...

class Button(BaseButton): ...
class HeaderButton(BaseButton): ...
class ListingButton(BaseButton): ...
class PageListingButton(ListingButton): ...
class BaseDropdownMenuButton(BaseButton): ...
class ButtonWithDropdown(BaseDropdownMenuButton): ...
class ButtonWithDropdownFromHook(BaseDropdownMenuButton): ...
