from wagtail.hooks import search_for_hooks as search_for_hooks
from wagtail.utils.registry import ObjectTypeRegistry as ObjectTypeRegistry

class ModelAdminURLFinder:
    edit_url_name: str | None
    permission_policy: object | None
    user: object | None
    def __init__(self, user=None) -> None: ...
    def construct_edit_url(self, instance): ...
    def get_edit_url(self, instance): ...

class NullAdminURLFinder:
    def __init__(self, user=None) -> None: ...
    def get_edit_url(self, instance) -> None: ...

finder_classes: ObjectTypeRegistry

def register_admin_url_finder(model, handler) -> None: ...

class AdminURLFinder:
    user: object | None
    finders_by_model: dict[type, ModelAdminURLFinder | NullAdminURLFinder]
    def __init__(self, user=None) -> None: ...
    def get_edit_url(self, instance): ...
