from _typeshed import Incomplete
from wagtail.admin import messages as messages
from wagtail.admin.localization import get_localized_response as get_localized_response
from wagtail.log_actions import LogContext as LogContext
from wagtail.permissions import page_permission_policy as page_permission_policy

def permission_denied(request): ...
def user_passes_test(test): ...
def permission_required(permission_name): ...
def any_permission_required(*perms): ...

class PermissionPolicyChecker:
    policy: Incomplete
    def __init__(self, policy) -> None: ...
    def require(self, action): ...
    def require_any(self, *actions): ...

def user_has_any_page_permission(user): ...
def reject_request(request): ...
def require_admin_access(view_func): ...
