def css_install_check(app_configs, **kwargs): ...
def base_form_class_check(app_configs, **kwargs): ...
def get_form_class_check(app_configs, **kwargs): ...
def inline_panel_model_panels_check(app_configs, **kwargs): ...
def check_panels_in_model(cls, context: str = "model"): ...
def wagtail_admin_base_url_check(app_configs, **kwargs): ...
def file_overwrite_check(app_configs, **kwargs): ...
def datetime_format_check(app_configs, **kwargs): ...
