from _typeshed import Incomplete
from wagtail import blocks as blocks
from wagtail.fields import RichTextField as RichTextField, StreamField as StreamField
from wagtail.utils.registry import ModelFieldRegistry as ModelFieldRegistry
from wagtail.utils.text import text_from_html as text_from_html

comparison_class_registry: Incomplete

def register_comparison_class(field_class, to=None, comparison_class=None, exact_class: bool = False) -> None: ...

class FieldComparison:
    is_field: bool
    is_child_relation: bool
    field: Incomplete
    val_a: Incomplete
    val_b: Incomplete
    def __init__(self, field, obj_a, obj_b) -> None: ...
    def field_label(self): ...
    def htmldiff(self): ...
    def has_changed(self): ...

class TextFieldComparison(FieldComparison):
    def htmldiff(self): ...

class RichTextFieldComparison(TextFieldComparison):
    def htmldiff(self): ...

def get_comparison_class_for_block(block): ...

class BlockComparison:
    block: Incomplete
    exists_a: Incomplete
    exists_b: Incomplete
    val_a: Incomplete
    val_b: Incomplete
    def __init__(self, block, exists_a, exists_b, val_a, val_b) -> None: ...
    def is_new(self): ...
    def is_deleted(self): ...
    def has_changed(self): ...
    def htmlvalue(self, val): ...
    def htmldiff(self): ...

class CharBlockComparison(BlockComparison):
    def htmldiff(self): ...
    def htmlvalue(self, val): ...

class RichTextBlockComparison(BlockComparison): ...

class StructBlockComparison(BlockComparison):
    def htmlvalue(self, val): ...
    def htmldiff(self): ...

class BaseSequenceBlockComparison(BlockComparison):
    @staticmethod
    def get_blocks_from_value(val) -> None: ...
    @staticmethod
    def get_blocks_by_id(a_blocks, b_blocks): ...
    def get_block_comparisons_by_id(self): ...
    def htmldiff(self): ...

class StreamBlockComparison(BaseSequenceBlockComparison):
    @staticmethod
    def get_blocks_from_value(val): ...
    def get_block_comparisons(self): ...
    def htmlvalue(self, val): ...

class ListBlockComparison(BaseSequenceBlockComparison):
    @staticmethod
    def get_blocks_from_value(val): ...
    def get_block_comparisons(self): ...

class StreamFieldComparison(FieldComparison):
    def has_block_ids(self, val): ...
    def htmldiff(self): ...

class ChoiceFieldComparison(FieldComparison):
    def htmldiff(self): ...

class M2MFieldComparison(FieldComparison):
    def get_items(self): ...
    def get_item_display(self, item): ...
    def htmldiff(self): ...
    def has_changed(self): ...

class TagsFieldComparison(M2MFieldComparison):
    def get_item_display(self, tag): ...

class ForeignObjectComparison(FieldComparison):
    def get_objects(self): ...
    def htmldiff(self): ...

class ChildRelationComparison:
    is_field: bool
    is_child_relation: bool
    field: Incomplete
    field_comparisons: Incomplete
    val_a: Incomplete
    val_b: Incomplete
    label: Incomplete
    def __init__(self, field, field_comparisons, obj_a, obj_b, label: str = '') -> None: ...
    def field_label(self): ...
    def get_mapping(self, objs_a, objs_b): ...
    def get_child_comparison(self, obj_a, obj_b): ...
    def get_child_comparisons(self): ...
    def has_changed(self): ...

class ChildObjectComparison:
    model: Incomplete
    field_comparisons: Incomplete
    obj_a: Incomplete
    obj_b: Incomplete
    def __init__(self, model, field_comparisons, obj_a, obj_b) -> None: ...
    def is_addition(self): ...
    def is_deletion(self): ...
    def get_position_change(self): ...
    def get_field_comparisons(self): ...
    def has_changed(self): ...
    def get_num_differences(self): ...

class TextDiff:
    changes: Incomplete
    separator: Incomplete
    def __init__(self, changes, separator: str = '') -> None: ...
    def to_html(self, tag: str = 'span', addition_class: str = 'addition', deletion_class: str = 'deletion'): ...

def diff_text(a, b): ...
