import functools
from _typeshed import Incomplete

WAGTAILADMIN_PROVIDED_LANGUAGES: Incomplete

def get_js_translation_strings(): ...
def get_available_admin_languages(): ...
@functools.cache
def get_available_admin_time_zones(): ...
def get_localized_response(view_func, request, *args, **kwargs): ...
