from _typeshed import Incomplete
from django.forms import MediaDefiningClass
from django.utils.functional import cached_property as cached_property
from wagtail import hooks as hooks
from wagtail.coreutils import cautious_slugify as cautious_slugify

class MenuItem(metaclass=MediaDefiningClass):
    label: Incomplete
    url: Incomplete
    classname: Incomplete
    icon_name: Incomplete
    name: Incomplete
    attrs: Incomplete
    order: Incomplete
    def __init__(self, label, url, name=None, classname: str = '', icon_name: str = '', attrs=None, order: int = 1000) -> None: ...
    def is_shown(self, request): ...
    def render_component(self, request): ...

class DismissibleMenuItemMixin:
    def __init__(self, *args, **kwargs) -> None: ...
    def render_component(self, request): ...

class DismissibleMenuItem(DismissibleMenuItemMixin, MenuItem): ...

class Menu:
    register_hook_name: Incomplete
    construct_hook_name: Incomplete
    initial_menu_items: Incomplete
    def __init__(self, register_hook_name=None, construct_hook_name=None, items=None) -> None: ...
    @cached_property
    def registered_menu_items(self): ...
    def menu_items_for_request(self, request): ...
    @property
    def media(self): ...
    def render_component(self, request): ...

class SubmenuMenuItem(MenuItem):
    menu: Incomplete
    def __init__(self, label, menu, **kwargs) -> None: ...
    def is_shown(self, request): ...
    def render_component(self, request): ...

class DismissibleSubmenuMenuItem(DismissibleMenuItemMixin, SubmenuMenuItem): ...

class AdminOnlyMenuItem(MenuItem):
    def is_shown(self, request): ...

class WagtailMenuRegisterable:
    menu_icon: str
    menu_label: str
    menu_name: str
    menu_order: int
    menu_url: Incomplete
    add_to_admin_menu: bool
    add_to_settings_menu: bool
    @cached_property
    def menu_item_class(self): ...
    def get_menu_item(self, order=None): ...
    @cached_property
    def menu_hook(self): ...
    def register_menu_item(self) -> None: ...

class WagtailMenuRegisterableGroup(WagtailMenuRegisterable):
    items: Incomplete
    menu_icon: str
    add_to_admin_menu: bool
    registerables: Incomplete
    def __init__(self) -> None: ...
    def get_submenu_items(self): ...
    def get_menu_item(self, order=None): ...

admin_menu: Incomplete
settings_menu: Incomplete
reports_menu: Incomplete
help_menu: Incomplete
