from wagtail.admin.mail import GroupApprovalTaskStateSubmissionEmailNotifier as GroupApprovalTaskStateSubmissionEmailNotifier, WorkflowStateApprovalEmailNotifier as WorkflowStateApprovalEmailNotifier, WorkflowStateRejectionEmailNotifier as WorkflowStateRejectionEmailNotifier, WorkflowStateSubmissionEmailNotifier as WorkflowStateSubmissionEmailNotifier
from wagtail.models import TaskState as TaskState, WorkflowState as WorkflowState
from wagtail.signals import task_submitted as task_submitted, workflow_approved as workflow_approved, workflow_rejected as workflow_rejected, workflow_submitted as workflow_submitted

task_submission_email_notifier: GroupApprovalTaskStateSubmissionEmailNotifier
workflow_submission_email_notifier: WorkflowStateSubmissionEmailNotifier
workflow_approval_email_notifier: WorkflowStateApprovalEmailNotifier
workflow_rejection_email_notifier: WorkflowStateRejectionEmailNotifier

def register_signal_handlers() -> None: ...
