from _typeshed import Incomplete
from wagtail import hooks as hooks
from wagtail.admin.ui.components import Component as Component
from wagtail.admin.utils import get_admin_base_url as get_admin_base_url
from wagtail.coreutils import accepts_kwarg as accepts_kwarg
from wagtail.models import Revision as Revision
from wagtail.models.pages import Page as Page
from wagtail.users.models import UserProfile as UserProfile
from wagtail.utils.deprecation import RemovedInWagtail80Warning as RemovedInWagtail80Warning

class BaseItem(Component):
    template_name: str
    def get_context_data(self, parent_context): ...

class AdminItem(BaseItem):
    template_name: str

class AccessibilityItem(BaseItem):
    in_editor: Incomplete
    def __init__(self, in_editor: bool = False) -> None: ...
    template_name: str
    axe_include: Incomplete
    axe_exclude: Incomplete
    axe_run_only: Incomplete
    axe_rules: Incomplete
    axe_custom_rules: Incomplete
    axe_custom_checks: Incomplete
    axe_messages: Incomplete
    def get_axe_include(self, request): ...
    def get_axe_exclude(self, request): ...
    def get_axe_run_only(self, request): ...
    def get_axe_rules(self, request): ...
    def get_axe_custom_rules(self, request): ...
    def get_axe_custom_checks(self, request): ...
    def get_axe_messages(self, request): ...
    def get_axe_context(self, request): ...
    def get_axe_options(self, request): ...
    def get_axe_spec(self, request): ...
    def get_axe_configuration(self, request): ...
    def get_context_data(self, parent_context): ...

class AddPageItem(BaseItem):
    template_name: str
    page: Incomplete
    parent_page: Incomplete
    def __init__(self, page) -> None: ...
    def render_html(self, parent_context): ...

class ExplorePageItem(BaseItem):
    template_name: str
    page: Incomplete
    parent_page: Incomplete
    def __init__(self, page) -> None: ...
    def render_html(self, parent_context): ...

class EditPageItem(BaseItem):
    template_name: str
    page: Incomplete
    def __init__(self, page) -> None: ...
    def render_html(self, parent_context): ...

def apply_userbar_hooks(request, items, page) -> None: ...

class Userbar(Component):
    template_name: str
    object: Incomplete
    position: Incomplete
    def __init__(self, *, object=None, position: str = 'bottom-right') -> None: ...
    def get_context_data(self, parent_context): ...
