from typing import Any
from wagtail import hooks as hooks
from wagtail.admin.ui.components import Component as Component
from wagtail.admin.utils import get_admin_base_url as get_admin_base_url
from wagtail.coreutils import accepts_kwarg as accepts_kwarg
from wagtail.models import Revision as Revision
from wagtail.models.pages import Page as Page
from wagtail.users.models import UserProfile as UserProfile
from wagtail.utils.deprecation import RemovedInWagtail80Warning as RemovedInWagtail80Warning

class BaseItem(Component):
    template_name: str
    def get_context_data(self, parent_context: dict[str, Any]) -> dict[str, Any]: ...

class AdminItem(BaseItem):
    template_name: str

class AccessibilityItem(BaseItem):
    in_editor: bool
    def __init__(self, in_editor: bool = False) -> None: ...
    template_name: str
    axe_include: list[str]
    axe_exclude: list[str | dict[str, list[str]]]
    axe_run_only: list[str] | None
    axe_rules: dict[str, dict[str, bool]]
    axe_custom_rules: list[dict[str, Any]]
    axe_custom_checks: list[dict[str, Any]]
    axe_messages: dict[str, dict[str, str]]
    def get_axe_include(self, request: Any) -> list[str]: ...
    def get_axe_exclude(self, request: Any) -> list[str | dict[str, list[str]]]: ...
    def get_axe_run_only(self, request: Any) -> list[str] | None: ...
    def get_axe_rules(self, request: Any) -> dict[str, dict[str, bool]]: ...
    def get_axe_custom_rules(self, request: Any) -> list[dict[str, Any]]: ...
    def get_axe_custom_checks(self, request: Any) -> list[dict[str, Any]]: ...
    def get_axe_messages(self, request: Any) -> dict[str, dict[str, str]]: ...
    def get_axe_context(self, request: Any) -> dict[str, Any]: ...
    def get_axe_options(self, request: Any) -> dict[str, Any]: ...
    def get_axe_spec(self, request: Any) -> dict[str, Any]: ...
    def get_axe_configuration(self, request: Any) -> dict[str, Any]: ...
    def get_context_data(self, parent_context: dict[str, Any]) -> dict[str, Any]: ...

class AddPageItem(BaseItem):
    template_name: str
    page: Page
    parent_page: Page | None
    def __init__(self, page: Page) -> None: ...
    def render_html(self, parent_context: dict[str, Any]) -> str: ...

class ExplorePageItem(BaseItem):
    template_name: str
    page: Page
    parent_page: Page | None
    def __init__(self, page: Page) -> None: ...
    def render_html(self, parent_context: dict[str, Any]) -> str: ...

class EditPageItem(BaseItem):
    template_name: str
    page: Page
    def __init__(self, page: Page) -> None: ...
    def render_html(self, parent_context: dict[str, Any]) -> str: ...

def apply_userbar_hooks(request: Any, items: list[BaseItem], page: Page | None) -> None: ...

class Userbar(Component):
    template_name: str
    object: Any
    position: str
    def __init__(self, *, object: Any = None, position: str = 'bottom-right') -> None: ...
    def get_context_data(self, parent_context: dict[str, Any]) -> dict[str, Any]: ...
