def get_admin_base_url(): ...
def get_valid_next_url_from_request(request): ...
def get_latest_str(obj): ...
def get_user_display_name(user): ...
def set_query_params(url: str, params: dict): ...
def get_keyboard_key_labels_from_request(request): ...
