from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property
from django.views.generic.base import View
from wagtail.admin import messages as messages
from wagtail.admin.action_menu import PageActionMenu as PageActionMenu
from wagtail.admin.telepath import JSContext as JSContext
from wagtail.admin.ui.autosave import AutosaveIndicator as AutosaveIndicator
from wagtail.admin.ui.components import MediaContainer as MediaContainer
from wagtail.admin.ui.side_panels import ChecksSidePanel as ChecksSidePanel, CommentsSidePanel as CommentsSidePanel, PageStatusSidePanel as PageStatusSidePanel, PreviewSidePanel as PreviewSidePanel
from wagtail.admin.utils import get_valid_next_url_from_request as get_valid_next_url_from_request, set_query_params as set_query_params
from wagtail.admin.views.generic import HookResponseMixin as HookResponseMixin, JsonPostResponseMixin as JsonPostResponseMixin
from wagtail.admin.views.generic.base import WagtailAdminTemplateMixin as WagtailAdminTemplateMixin
from wagtail.models import BaseViewRestriction as BaseViewRestriction, Locale as Locale, Page as Page, PageSubscription as PageSubscription, PageViewRestriction as PageViewRestriction
from wagtail.signals import init_new_page as init_new_page

def add_subpage(request, parent_page_id): ...

class CreateView(WagtailAdminTemplateMixin, HookResponseMixin, JsonPostResponseMixin, View):
    template_name: str
    page_title: Incomplete
    edit_url_name: str
    parent_page: Incomplete
    parent_page_perms: Incomplete
    page_content_type: Incomplete
    page_class: Incomplete
    locale: Incomplete
    page: Incomplete
    translations: Incomplete
    edit_handler: Incomplete
    form_class: Incomplete
    subscription: Incomplete
    next_url: Incomplete
    autosave_interval: Incomplete
    autosave_enabled: Incomplete
    def dispatch(self, request, content_type_app_name, content_type_model_name, parent_page_id): ...
    form: Incomplete
    def post(self, request): ...
    @cached_property
    def action_name_and_method(self): ...
    @property
    def action_name(self): ...
    @property
    def action_method(self): ...
    def form_valid(self, form): ...
    def get_page_subtitle(self): ...
    def get_edit_message_button(self): ...
    def get_edit_url(self): ...
    def get_view_draft_message_button(self): ...
    def get_view_live_message_button(self): ...
    def set_default_privacy_setting(self) -> None: ...
    def save_action(self): ...
    def publish_action(self): ...
    def submit_action(self): ...
    def redirect_away(self): ...
    def redirect_and_remain(self): ...
    has_unsaved_changes: bool
    def form_invalid(self, form): ...
    def get(self, request): ...
    def get_preview_url(self): ...
    def get_side_panels(self): ...
    def get_context_data(self, **kwargs): ...
    def get_translations(self): ...
