from django.contrib.contenttypes.models import ContentType
from django.utils.functional import cached_property as cached_property
from django.views.generic.base import View
from wagtail.admin import messages as messages
from wagtail.admin.action_menu import PageActionMenu as PageActionMenu
from wagtail.telepath import JSContext as JSContext
from wagtail.admin.ui.autosave import AutosaveIndicator as AutosaveIndicator
from wagtail.admin.ui.components import MediaContainer as MediaContainer
from wagtail.admin.ui.side_panels import ChecksSidePanel as ChecksSidePanel, CommentsSidePanel as CommentsSidePanel, PageStatusSidePanel as PageStatusSidePanel, PreviewSidePanel as PreviewSidePanel
from wagtail.admin.utils import get_valid_next_url_from_request as get_valid_next_url_from_request, set_query_params as set_query_params
from wagtail.admin.views.generic import HookResponseMixin as HookResponseMixin, JsonPostResponseMixin as JsonPostResponseMixin
from wagtail.admin.views.generic.base import WagtailAdminTemplateMixin as WagtailAdminTemplateMixin
from wagtail.models import BaseViewRestriction as BaseViewRestriction, Locale as Locale, Page as Page, PageSubscription as PageSubscription, PageViewRestriction as PageViewRestriction
from wagtail.signals import init_new_page as init_new_page

def add_subpage(request, parent_page_id): ...

class CreateView(WagtailAdminTemplateMixin, HookResponseMixin, JsonPostResponseMixin, View):
    template_name: str
    page_title: str
    edit_url_name: str
    parent_page: Page
    parent_page_perms: object
    page_content_type: ContentType
    page_class: type[Page]
    locale: Locale | None
    page: Page
    translations: list
    edit_handler: object
    form_class: type
    subscription: PageSubscription
    next_url: str | None
    autosave_interval: object
    autosave_enabled: object
    def dispatch(self, request, content_type_app_name, content_type_model_name, parent_page_id): ...
    form: object
    def post(self, request): ...
    @cached_property
    def action_name_and_method(self): ...
    @property
    def action_name(self): ...
    @property
    def action_method(self): ...
    def form_valid(self, form): ...
    def get_page_subtitle(self): ...
    def get_edit_message_button(self): ...
    def get_edit_url(self): ...
    def get_view_draft_message_button(self): ...
    def get_view_live_message_button(self): ...
    def set_default_privacy_setting(self) -> None: ...
    def save_action(self): ...
    def publish_action(self): ...
    def submit_action(self): ...
    def redirect_away(self): ...
    def redirect_and_remain(self): ...
    has_unsaved_changes: bool
    def form_invalid(self, form): ...
    def get(self, request): ...
    def get_preview_url(self): ...
    def get_side_panels(self): ...
    def get_context_data(self, **kwargs): ...
    def get_translations(self): ...
