from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property
from django.views.generic.base import View
from wagtail.actions.publish_page_revision import PublishPageRevisionAction as PublishPageRevisionAction
from wagtail.admin import messages as messages
from wagtail.admin.action_menu import PageActionMenu as PageActionMenu
from wagtail.admin.mail import send_notification as send_notification
from wagtail.admin.models import EditingSession as EditingSession
from wagtail.admin.telepath import JSContext as JSContext
from wagtail.admin.ui.autosave import AutosaveIndicator as AutosaveIndicator
from wagtail.admin.ui.components import MediaContainer as MediaContainer
from wagtail.admin.ui.editing_sessions import EditingSessionsModule as EditingSessionsModule
from wagtail.admin.ui.side_panels import ChecksSidePanel as ChecksSidePanel, CommentsSidePanel as CommentsSidePanel, PageStatusSidePanel as PageStatusSidePanel, PreviewSidePanel as PreviewSidePanel
from wagtail.admin.utils import get_valid_next_url_from_request as get_valid_next_url_from_request
from wagtail.admin.views.generic import HookResponseMixin as HookResponseMixin, JsonPostResponseMixin as JsonPostResponseMixin
from wagtail.admin.views.generic.base import WagtailAdminTemplateMixin as WagtailAdminTemplateMixin
from wagtail.exceptions import PageClassNotFoundError as PageClassNotFoundError
from wagtail.locks import BasicLock as BasicLock, ScheduledForPublishLock as ScheduledForPublishLock, WorkflowLock as WorkflowLock
from wagtail.models import COMMENTS_RELATION_NAME as COMMENTS_RELATION_NAME, Comment as Comment, CommentReply as CommentReply, Page as Page, PageSubscription as PageSubscription, Revision as Revision, WorkflowState as WorkflowState, get_default_page_content_type as get_default_page_content_type
from wagtail.utils.timestamps import render_timestamp as render_timestamp

class EditView(WagtailAdminTemplateMixin, HookResponseMixin, JsonPostResponseMixin, View):
    partials_template_name: str
    def get_page_title(self): ...
    def get_page_subtitle(self): ...
    def get_template_names(self): ...
    def add_save_confirmation_message(self) -> None: ...
    def get_commenting_changes(self): ...
    def send_commenting_notifications(self, changes): ...
    def log_commenting_changes(self, changes, revision) -> None: ...
    def get_edit_message_button(self): ...
    def get_view_draft_message_button(self): ...
    def get_view_live_message_button(self): ...
    def get_compare_with_live_message_button(self): ...
    def get_page_for_status(self): ...
    def get_object(self): ...
    def get_edit_url(self): ...
    real_page_record: Incomplete
    latest_revision: Incomplete
    scheduled_revision: Incomplete
    page_content_type: Incomplete
    page_class: Incomplete
    revision_id: Incomplete
    is_reverting: Incomplete
    previous_revision: Incomplete
    page: Incomplete
    parent: Incomplete
    scheduled_page: Incomplete
    page_perms: Incomplete
    lock: Incomplete
    locked_for_user: Incomplete
    next_url: Incomplete
    edit_handler: Incomplete
    form_class: Incomplete
    workflow_state: Incomplete
    locale: Incomplete
    translations: Incomplete
    workflow_tasks: Incomplete
    has_unsaved_changes: bool
    errors_debug: Incomplete
    autosave_interval: Incomplete
    autosave_enabled: Incomplete
    def dispatch(self, request, page_id, **kwargs): ...
    form: Incomplete
    def get(self, request, *args, **kwargs): ...
    def add_cancel_workflow_confirmation_message(self) -> None: ...
    @cached_property
    def is_cancelling_workflow(self): ...
    @cached_property
    def hydrate_create_view(self): ...
    @cached_property
    def latest_revision_created_at(self): ...
    @cached_property
    def is_out_of_date(self): ...
    def post(self, request, *args, **kwargs): ...
    workflow_action: Incomplete
    def workflow_action_is_valid(self): ...
    @cached_property
    def action_name_and_method(self): ...
    @property
    def action_name(self): ...
    @property
    def action_method(self): ...
    has_content_changes: Incomplete
    def form_valid(self, form): ...
    def save_action(self): ...
    def publish_action(self): ...
    def submit_action(self): ...
    def restart_workflow_action(self): ...
    def perform_workflow_action(self): ...
    def cancel_workflow_action(self): ...
    def redirect_away(self): ...
    def redirect_and_remain(self): ...
    def form_invalid(self, form): ...
    def get_preview_url(self): ...
    def get_history_url(self): ...
    def get_side_panels(self): ...
    def get_editing_sessions(self): ...
    def get_action_menu(self): ...
    def get_context_data(self, **kwargs): ...
    def get_translations(self): ...
