from django.contrib.contenttypes.models import ContentType
from django.utils.functional import cached_property
from wagtail.admin.views.generic.preview import PreviewOnEdit as GenericPreviewOnEdit
from wagtail.models.pages import Page as Page

def view_draft(request, page_id): ...

class PreviewOnEdit(GenericPreviewOnEdit):
    def get_object(self): ...
    def get_form(self, query_dict): ...

class PreviewOnCreate(PreviewOnEdit):
    @cached_property
    def content_type(self) -> ContentType: ...
    @cached_property
    def parent_object_id(self) -> int: ...
    def get_object(self): ...
    def get_form(self, query_dict): ...
