from wagtail.admin.views.generic.preview import PreviewOnEdit as GenericPreviewOnEdit
from wagtail.models import Page as Page

def view_draft(request, page_id): ...

class PreviewOnEdit(GenericPreviewOnEdit):
    @property
    def session_key(self): ...
    def get_object(self): ...
    def get_form(self, query_dict): ...

class PreviewOnCreate(PreviewOnEdit):
    @property
    def session_key(self): ...
    def get_object(self): ...
    def get_form(self, query_dict): ...
