from wagtail import hooks as hooks
from wagtail.actions.unpublish_page import UnpublishPageAction as UnpublishPageAction
from wagtail.admin.utils import get_valid_next_url_from_request as get_valid_next_url_from_request
from wagtail.admin.views.generic.models import UnpublishView as UnpublishView
from wagtail.models.pages import Page as Page

class Unpublish(UnpublishView):
    model = Page
    index_url_name: str
    edit_url_name: str
    unpublish_url_name: str
    usage_url_name: str
    success_message: str
    template_name: str
    header_icon: str
    def setup(self, request, page_id, *args, **kwargs): ...
    def get_object(self, queryset=None): ...
    def get_object_display_title(self): ...
    def dispatch(self, request, *args, **kwargs): ...
    def get_success_message(self): ...
    def get_next_url(self): ...
    def get_objects_to_unpublish(self): ...
    def unpublish(self): ...
    def get_context_data(self, **kwargs): ...
