from collections import OrderedDict
from collections.abc import Generator, Iterable
from typing import Any

from django.core.management.base import BaseCommand
from django.db import transaction
from django.db.models import QuerySet

from wagtail.search.backends.base import BaseSearchBackend

DEFAULT_CHUNK_SIZE: int

def group_models_by_index(backend: BaseSearchBackend, models: list[type]) -> OrderedDict[Any, list[type]]: ...

class Command(BaseCommand):
    verbosity: int
    def write(self, *args: Any, **kwargs: Any) -> None: ...
    def update_backend(self, backend_name: str, schema_only: bool = False, chunk_size: int = ...) -> None: ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, **options: Any) -> None: ...
    def print_newline(self) -> None: ...
    def print_iter_progress(self, iterable: Iterable[Any]) -> Generator[Any]: ...
    @transaction.atomic
    def queryset_chunks(self, qs: QuerySet[Any], chunk_size: int = ...) -> Generator[list[Any]]: ...
