from .base import BaseBackend

__all__ = ['AzureBaseBackend', 'AzureFrontDoorBackend', 'AzureCdnBackend']

class AzureBaseBackend(BaseBackend):
    def __init__(self, params) -> None: ...
    def purge_batch(self, urls) -> None: ...
    def purge(self, url) -> None: ...

class AzureFrontDoorBackend(AzureBaseBackend):
    def __init__(self, params) -> None: ...

class AzureCdnBackend(AzureBaseBackend):
    def __init__(self, params) -> None: ...
