from _typeshed import Incomplete

__all__ = ["BaseBackend"]

class BaseBackend:
    hostnames: Incomplete
    def __init__(self, params) -> None: ...
    def purge(self, url) -> None: ...
    def purge_batch(self, urls) -> None: ...
    def invalidates_hostname(self, hostname) -> bool: ...
