from django.db.migrations.operations.base import Operation
from django.db import migrations

def add_choose_permission_to_admin_groups(apps, _schema_editor) -> None: ...
def remove_choose_permission(apps, _schema_editor) -> None: ...
def get_choose_permission(apps): ...
def copy_choose_permission_to_collections(apps, _schema_editor) -> None: ...
def remove_choose_permission_from_collections(apps, _schema_editor) -> None: ...

class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]]
    operations: list[Operation]
