from _typeshed import Incomplete
from collections.abc import Generator
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db.models import Model
from wagtail.rich_text.feature_registry import FeatureRegistry as FeatureRegistry
from wagtail.rich_text.rewriters import EmbedRewriter as EmbedRewriter, LinkRewriter as LinkRewriter, MultiRuleRewriter as MultiRuleRewriter

features: Incomplete

def get_rewriter(): ...
def expand_db_html(html): ...
def extract_references_from_rich_text(html) -> Generator[Incomplete, Incomplete]: ...
def get_text_for_indexing(richtext): ...

class RichText:
    source: Incomplete
    def __init__(self, source) -> None: ...
    def __html__(self): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...

class EntityHandler:
    @staticmethod
    def get_model() -> None: ...
    @classmethod
    def get_instance(cls, attrs: dict) -> Model: ...
    @classmethod
    def get_many(cls, attrs_list: list[dict]) -> list[Model]: ...
    @staticmethod
    def expand_db_attributes(attrs: dict) -> str: ...
    @classmethod
    def expand_db_attributes_many(cls, attrs_list: list[dict]) -> list[str]: ...
    @classmethod
    def extract_references(cls, attrs): ...

class LinkHandler(EntityHandler): ...
class EmbedHandler(EntityHandler): ...

class RichTextMinLengthValidator(MinLengthValidator):
    def clean(self, x): ...

class RichTextMaxLengthValidator(MaxLengthValidator):
    def clean(self, x): ...
