from _typeshed import Incomplete
from wagtail import hooks as hooks

class FeatureRegistry:
    has_scanned_for_features: bool
    plugins_by_editor: Incomplete
    default_features: Incomplete
    link_types: Incomplete
    embed_types: Incomplete
    converter_rules_by_converter: Incomplete
    def __init__(self) -> None: ...
    def get_default_features(self): ...
    def register_editor_plugin(self, editor_name, feature_name, plugin) -> None: ...
    def get_editor_plugin(self, editor_name, feature_name): ...
    def register_link_type(self, handler) -> None: ...
    def get_link_types(self): ...
    def register_embed_type(self, handler) -> None: ...
    def get_embed_types(self): ...
    def register_converter_rule(self, converter_name, feature_name, rule) -> None: ...
    def get_converter_rule(self, converter_name, feature_name): ...
    @staticmethod
    def function_as_entity_handler(identifier, fn): ...
