from _typeshed import Incomplete
from collections.abc import Callable as Callable, Generator
from django.utils.functional import cached_property as cached_property

FIND_A_TAG: Incomplete
FIND_EMBED_TAG: Incomplete
FIND_ATTRS: Incomplete

def extract_attrs(attr_string: str) -> dict: ...

class TagMatch:
    match: Incomplete
    replacement: Incomplete
    def __init__(self, match) -> None: ...
    @cached_property
    def attrs(self): ...
    @property
    def start(self): ...
    @property
    def end(self): ...

class TagRewriter:
    rules: Incomplete
    bulk_rules: Incomplete
    reference_extractors: Incomplete
    def __init__(self, rules=None, bulk_rules=None, reference_extractors=None) -> None: ...
    def get_opening_tag_regex(self) -> None: ...
    def get_tag_type_from_attrs(self, attrs) -> None: ...
    def get_tag_replacements(self, tag_type, attrs_list) -> None: ...
    def __call__(self, html: str) -> str: ...
    def extract_tags(self, html: str) -> dict[str, list[TagMatch]]: ...
    def convert_rule_to_bulk_rule(self, rule: Callable) -> Callable: ...
    def extract_references(self, html) -> Generator[Incomplete, Incomplete, Incomplete]: ...

class EmbedRewriter(TagRewriter):
    def get_opening_tag_regex(self): ...
    def get_tag_type_from_attrs(self, attrs): ...
    def get_tag_replacements(self, tag_type, attrs_list): ...

class LinkRewriter(TagRewriter):
    def get_opening_tag_regex(self): ...
    def get_tag_type_from_attrs(self, attrs): ...
    def get_tag_replacements(self, tag_type, attrs_list): ...

class MultiRuleRewriter:
    rewriters: Incomplete
    def __init__(self, rewriters) -> None: ...
    def __call__(self, html): ...
    def extract_references(self, html) -> Generator[Incomplete, Incomplete]: ...
