from _typeshed import Incomplete
from django.contrib.sitemaps import Sitemap as DjangoSitemap

class Sitemap(DjangoSitemap):
    request: Incomplete
    def __init__(self, request=None) -> None: ...
    def location(self, obj): ...
    def lastmod(self, obj): ...
    def get_wagtail_site(self): ...
    def items(self): ...
