from _typeshed import Incomplete
from django.core.exceptions import PermissionDenied
from wagtail.log_actions import log as log

class ConvertAliasPageError(RuntimeError): ...
class ConvertAliasPagePermissionError(PermissionDenied): ...

class ConvertAliasPageAction:
    page: Incomplete
    log_action: Incomplete
    user: Incomplete
    def __init__(self, page, *, log_action: str = 'wagtail.convert_alias', user=None) -> None: ...
    def check(self, skip_permission_checks: bool = False) -> None: ...
    def execute(self, skip_permission_checks: bool = False): ...
