from _typeshed import Incomplete
from django.core.exceptions import PermissionDenied
from wagtail.log_actions import log as log

class DeletePagePermissionError(PermissionDenied): ...

class DeletePageAction:
    page: Incomplete
    user: Incomplete
    def __init__(self, page, user) -> None: ...
    def check(self, skip_permission_checks: bool = False) -> None: ...
    def execute(self, *args, skip_permission_checks: bool = False, **kwargs): ...
    def log_deletion(self, page) -> None: ...
