from modelsearch.backends.elasticsearch9 import *
from modelsearch.backends.elasticsearch9 import Elasticsearch9AutocompleteQueryCompiler as _Elasticsearch9AutocompleteQueryCompiler, Elasticsearch9SearchBackend as _Elasticsearch9SearchBackend, Elasticsearch9SearchQueryCompiler as _Elasticsearch9SearchQueryCompiler
from wagtail.search.backends.deprecation import IndexOptionMixin as IndexOptionMixin, LegacyContentTypeMatchMixin as LegacyContentTypeMatchMixin

class Elasticsearch9SearchQueryCompiler(LegacyContentTypeMatchMixin, _Elasticsearch9SearchQueryCompiler): ...
class Elasticsearch9AutocompleteQueryCompiler(LegacyContentTypeMatchMixin, _Elasticsearch9AutocompleteQueryCompiler): ...

class Elasticsearch9SearchBackend(IndexOptionMixin, _Elasticsearch9SearchBackend):
    query_compiler_class = Elasticsearch9SearchQueryCompiler
    autocomplete_query_compiler_class = Elasticsearch9AutocompleteQueryCompiler
SearchBackend = Elasticsearch9SearchBackend
