from modelsearch.backends.opensearch2 import *
from modelsearch.backends.opensearch2 import OpenSearch2AutocompleteQueryCompiler as _OpenSearch2AutocompleteQueryCompiler, OpenSearch2SearchBackend as _OpenSearch2SearchBackend, OpenSearch2SearchQueryCompiler as _OpenSearch2SearchQueryCompiler
from wagtail.search.backends.deprecation import IndexOptionMixin as IndexOptionMixin, LegacyContentTypeMatchMixin as LegacyContentTypeMatchMixin

class OpenSearch2SearchQueryCompiler(LegacyContentTypeMatchMixin, _OpenSearch2SearchQueryCompiler): ...
class OpenSearch2AutocompleteQueryCompiler(LegacyContentTypeMatchMixin, _OpenSearch2AutocompleteQueryCompiler): ...

class OpenSearch2SearchBackend(IndexOptionMixin, _OpenSearch2SearchBackend):
    query_compiler_class = OpenSearch2SearchQueryCompiler
    autocomplete_query_compiler_class = OpenSearch2AutocompleteQueryCompiler
SearchBackend = OpenSearch2SearchBackend
