from modelsearch.backends.opensearch3 import *
from modelsearch.backends.opensearch3 import OpenSearch3AutocompleteQueryCompiler as _OpenSearch3AutocompleteQueryCompiler, OpenSearch3SearchBackend as _OpenSearch3SearchBackend, OpenSearch3SearchQueryCompiler as _OpenSearch3SearchQueryCompiler
from wagtail.search.backends.deprecation import IndexOptionMixin as IndexOptionMixin, LegacyContentTypeMatchMixin as LegacyContentTypeMatchMixin

class OpenSearch3SearchQueryCompiler(LegacyContentTypeMatchMixin, _OpenSearch3SearchQueryCompiler): ...
class OpenSearch3AutocompleteQueryCompiler(LegacyContentTypeMatchMixin, _OpenSearch3AutocompleteQueryCompiler): ...

class OpenSearch3SearchBackend(IndexOptionMixin, _OpenSearch3SearchBackend):
    query_compiler_class = OpenSearch3SearchQueryCompiler
    autocomplete_query_compiler_class = OpenSearch3AutocompleteQueryCompiler
SearchBackend = OpenSearch3SearchBackend
