from _typeshed import Incomplete
from wagtail.utils.urlpatterns import decorate_urlpatterns as decorate_urlpatterns

class WagtailAPIRouter:
    url_namespace: Incomplete
    def __init__(self, url_namespace) -> None: ...
    def register_endpoint(self, name, class_) -> None: ...
    def get_model_endpoint(self, model): ...
    def get_model_listing_urlpath(self, model): ...
    def get_object_detail_urlpath(self, model, pk): ...
    def wrap_view(self, func): ...
    def get_urlpatterns(self): ...
    @property
    def urls(self): ...
