from .utils import get_object_detail_url as get_object_detail_url
from _typeshed import Incomplete
from rest_framework import relations, serializers
from rest_framework.fields import Field

class TypeField(Field):
    def get_attribute(self, instance): ...
    def to_representation(self, obj): ...

class DetailUrlField(Field):
    def get_attribute(self, instance): ...
    def to_representation(self, url): ...

class PageHtmlUrlField(Field):
    def get_attribute(self, instance): ...
    def to_representation(self, page): ...

class PageTypeField(Field):
    def get_attribute(self, instance): ...
    def to_representation(self, page): ...

class PageLocaleField(Field):
    def get_attribute(self, instance): ...
    def to_representation(self, page): ...

class RelatedField(relations.RelatedField):
    serializer_class: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def to_representation(self, value): ...

class PageParentField(relations.RelatedField):
    def get_attribute(self, instance): ...
    def to_representation(self, value): ...

class PageAliasOfField(relations.RelatedField):
    def get_attribute(self, instance): ...
    def to_representation(self, value): ...

class ChildRelationField(Field):
    serializer_class: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def to_representation(self, value): ...

class StreamField(Field):
    def to_representation(self, value): ...

class TagsField(Field):
    def to_representation(self, value): ...

class BaseSerializer(serializers.ModelSerializer):
    serializer_field_mapping: Incomplete
    serializer_related_field = RelatedField
    type: Incomplete
    detail_url: Incomplete
    def to_representation(self, instance): ...
    def build_property_field(self, field_name, model_class): ...
    def build_relational_field(self, field_name, relation_info): ...

class PageSerializer(BaseSerializer):
    type: Incomplete
    locale: Incomplete
    html_url: Incomplete
    parent: Incomplete
    alias_of: Incomplete
    def build_relational_field(self, field_name, relation_info): ...

def get_serializer_class(model, field_names, meta_fields, field_serializer_overrides=None, child_serializer_classes=None, base=...): ...
