from typing import Any

from django.db import models

def purge_page_from_cache(instance: models.Model, **kwargs: Any) -> None: ...
def purge_image_from_cache(instance: models.Model, **kwargs: Any) -> None: ...
def purge_document_from_cache(instance: models.Model, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
def unregister_signal_handlers() -> None: ...
