from .utils import get_base_url as get_base_url
from wagtail.contrib.frontend_cache.utils import purge_url_from_cache as purge_url_from_cache
from wagtail.documents import get_document_model as get_document_model
from wagtail.images import get_image_model as get_image_model
from wagtail.models import get_page_models as get_page_models
from wagtail.signals import page_published as page_published, page_unpublished as page_unpublished

def purge_page_from_cache(instance, **kwargs) -> None: ...
def purge_image_from_cache(instance, **kwargs) -> None: ...
def purge_document_from_cache(instance, **kwargs) -> None: ...
def register_signal_handlers() -> None: ...
def unregister_signal_handlers() -> None: ...
