from wagtail.coreutils import resolve_model_string as resolve_model_string
from wagtail.models import Page as Page, Site as Site

class BadRequestError(Exception): ...

def get_base_url(request=None): ...
def get_full_url(request, path): ...
def get_object_detail_url(router, request, model, pk): ...
def page_models_from_string(string): ...

class FieldsParameterParseError(ValueError): ...

def parse_fields_parameter(fields_str): ...
def parse_boolean(value): ...
