from .filters import AncestorOfFilter as AncestorOfFilter, ChildOfFilter as ChildOfFilter, DescendantOfFilter as DescendantOfFilter, FieldsFilter as FieldsFilter, LocaleFilter as LocaleFilter, OrderingFilter as OrderingFilter, SearchFilter as SearchFilter, TranslationOfFilter as TranslationOfFilter
from .pagination import WagtailPagination as WagtailPagination
from .serializers import BaseSerializer as BaseSerializer, PageSerializer as PageSerializer, get_serializer_class as get_serializer_class
from .utils import BadRequestError as BadRequestError, get_object_detail_url as get_object_detail_url, page_models_from_string as page_models_from_string, parse_fields_parameter as parse_fields_parameter
from _typeshed import Incomplete
from django.utils.functional import classproperty
from rest_framework.viewsets import GenericViewSet
from wagtail.api import APIField as APIField
from wagtail.models import Page as Page, PageViewRestriction as PageViewRestriction, Site as Site

class BaseAPIViewSet(GenericViewSet):
    @classproperty
    def renderer_classes(cls): ...
    pagination_class = WagtailPagination
    base_serializer_class = BaseSerializer
    filter_backends: Incomplete
    model: Incomplete
    known_query_parameters: Incomplete
    find_query_parameters: Incomplete
    body_fields: Incomplete
    meta_fields: Incomplete
    listing_default_fields: Incomplete
    nested_default_fields: Incomplete
    detail_only_fields: Incomplete
    name: Incomplete
    seen_types: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_queryset(self): ...
    def listing_view(self, request): ...
    def detail_view(self, request, pk): ...
    def find_view(self, request): ...
    def find_object(self, queryset, request): ...
    def handle_exception(self, exc): ...
    @classmethod
    def get_body_fields(cls, model): ...
    @classmethod
    def get_body_fields_names(cls, model): ...
    @classmethod
    def get_meta_fields(cls, model): ...
    @classmethod
    def get_meta_fields_names(cls, model): ...
    @classmethod
    def get_field_serializer_overrides(cls, model): ...
    @classmethod
    def get_available_fields(cls, model, db_fields_only: bool = False): ...
    @classmethod
    def get_detail_default_fields(cls, model): ...
    @classmethod
    def get_listing_default_fields(cls, model): ...
    @classmethod
    def get_nested_default_fields(cls, model): ...
    def check_query_parameters(self, queryset) -> None: ...
    def get_serializer_class(self): ...
    def get_serializer_context(self): ...
    def get_renderer_context(self): ...
    @classmethod
    def get_urlpatterns(cls): ...
    @classmethod
    def get_model_listing_urlpath(cls, model, namespace: str = ''): ...
    @classmethod
    def get_object_detail_urlpath(cls, model, pk, namespace: str = ''): ...

class PagesAPIViewSet(BaseAPIViewSet):
    base_serializer_class = PageSerializer
    filter_backends: Incomplete
    known_query_parameters: Incomplete
    find_query_parameters: Incomplete
    body_fields: Incomplete
    meta_fields: Incomplete
    listing_default_fields: Incomplete
    nested_default_fields: Incomplete
    detail_only_fields: Incomplete
    name: str
    model = Page
    @classmethod
    def get_detail_default_fields(cls, model): ...
    @classmethod
    def get_listing_default_fields(cls, model): ...
    def get_root_page(self): ...
    def get_base_queryset(self): ...
    def get_queryset(self): ...
    def get_object(self): ...
    def find_object(self, queryset, request): ...
    def get_serializer_context(self): ...
