import functools
import re
from _typeshed import Incomplete
from collections.abc import Iterable
from django.db.models import Model
from django.db.models.base import ModelBase
from django.http import HttpRequest
from typing import Any
from wagtail.models import Site as Site

logger: Incomplete
WAGTAIL_APPEND_SLASH: Incomplete

def camelcase_to_underscore(str): ...
def string_to_ascii(value): ...
def get_model_string(model): ...
def resolve_model_string(model_string, default_app=None): ...

SLUGIFY_RE: Incomplete

def cautious_slugify(value): ...
def safe_snake_case(value): ...
def get_content_type_label(content_type): ...
def accepts_kwarg(func, kwarg): ...

class InvokeViaAttributeShortcut:
    obj: Incomplete
    method_name: Incomplete
    def __init__(self, obj, method_name) -> None: ...
    def __getattr__(self, name): ...

def find_available_slug(parent, requested_slug, ignore_page_id=None): ...
@functools.cache
def get_content_languages(): ...
def get_supported_content_language_variant(lang_code, strict: bool = False): ...
def get_locales_display_names() -> dict: ...
def reset_cache(**kwargs) -> None: ...
def multigetattr(item, accessor): ...
def get_dummy_request(*, path: str = '/', site: Site = None) -> HttpRequest: ...
def safe_md5(data: bytes = b'', usedforsecurity: bool = True): ...

class BatchProcessor:
    max_size: Incomplete
    items: Incomplete
    added_count: int
    def __init__(self, max_size: int) -> None: ...
    def __len__(self) -> int: ...
    def add(self, item: Any) -> None: ...
    def extend(self, iterable: Iterable[Any]) -> None: ...
    def process(self) -> None: ...
    def pre_process(self) -> None: ...
    def post_process(self) -> None: ...

class BatchCreator(BatchProcessor):
    model: ModelBase
    ignore_conflicts: Incomplete
    created_count: int
    def __init__(self, max_size: int, *, model: ModelBase = None, ignore_conflicts: bool = False) -> None: ...
    def initialize_instance(self, kwargs): ...
    def add(self, *, instance: Model = None, **kwargs) -> None: ...
    def extend(self, iterable: Iterable[Model | dict[str, Any]]) -> None: ...
    def get_summary(self): ...

def make_wagtail_template_fragment_key(fragment_name, page, site, vary_on=None): ...
def get_js_regex(regex: re.Pattern | str | bytes | None = None, base_js_flags: str | None = 'gu') -> list[str]: ...
