import types
from collections.abc import Callable
from contextlib import ContextDecorator
from typing import overload

@overload
def register(hook_name: str) -> Callable[[Callable[..., object]], Callable[..., object]]: ...
@overload
def register(hook_name: str, fn: Callable[..., object], order: int = 0) -> None: ...

class TemporaryHook(ContextDecorator):
    hooks: list[tuple[str, Callable[..., object]]]
    order: int
    def __init__(self, hooks: list[tuple[str, Callable[..., object]]], order: int) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

def register_temporarily(hook_name_or_hooks: str | list[tuple[str, Callable[..., object]]], fn: Callable[..., object] | None = None, *, order: int = 0) -> TemporaryHook: ...
def search_for_hooks() -> None: ...
def get_hooks(hook_name: str) -> list[Callable[..., object]]: ...
