from typing import Any

from django.contrib.auth.models import AbstractBaseUser

class BaseLock:
    object: Any
    is_page: bool
    model_name: str
    def __init__(self, object: Any) -> None: ...
    def for_user(self, user: AbstractBaseUser) -> bool: ...
    def get_message(self, user: AbstractBaseUser) -> str | None: ...
    def get_icon(self, user: AbstractBaseUser) -> str: ...
    def get_locked_by(self, user: AbstractBaseUser) -> str: ...
    def get_description(self, user: AbstractBaseUser) -> str: ...
    def get_context_for_user(self, user: AbstractBaseUser, parent_context: dict[str, Any] | None = None) -> dict[str, Any]: ...

class BasicLock(BaseLock):
    def for_user(self, user: AbstractBaseUser) -> bool: ...
    def get_message(self, user: AbstractBaseUser) -> str: ...
    def get_locked_by(self, user: AbstractBaseUser) -> str: ...
    def get_description(self, user: AbstractBaseUser) -> str: ...

class WorkflowLock(BaseLock):
    task: Any
    def __init__(self, object: Any, task: Any) -> None: ...
    def for_user(self, user: AbstractBaseUser) -> bool: ...
    def get_message(self, user: AbstractBaseUser) -> str | None: ...
    def get_icon(self, user: AbstractBaseUser, can_lock: bool = False) -> str: ...
    def get_locked_by(self, user: AbstractBaseUser, can_lock: bool = False) -> str: ...
    def get_description(self, user: AbstractBaseUser, can_lock: bool = False) -> str: ...
    def get_context_for_user(self, user: AbstractBaseUser, parent_context: dict[str, Any] | None = None) -> dict[str, Any]: ...

class ScheduledForPublishLock(BaseLock):
    def for_user(self, user: AbstractBaseUser) -> bool: ...
    def get_message(self, user: AbstractBaseUser) -> str: ...
    def get_locked_by(self, user: AbstractBaseUser) -> str: ...
    def get_description(self, user: AbstractBaseUser) -> str: ...
