from _typeshed import Incomplete
from wagtail.admin.utils import get_latest_str as get_latest_str, get_user_display_name as get_user_display_name
from wagtail.utils.timestamps import render_timestamp as render_timestamp

class BaseLock:
    object: Incomplete
    is_page: Incomplete
    model_name: Incomplete
    def __init__(self, object) -> None: ...
    def for_user(self, user): ...
    def get_message(self, user) -> None: ...
    def get_icon(self, user): ...
    def get_locked_by(self, user): ...
    def get_description(self, user): ...
    def get_context_for_user(self, user, parent_context=None): ...

class BasicLock(BaseLock):
    def for_user(self, user): ...
    def get_message(self, user): ...
    def get_locked_by(self, user): ...
    def get_description(self, user): ...

class WorkflowLock(BaseLock):
    task: Incomplete
    def __init__(self, object, task) -> None: ...
    def for_user(self, user): ...
    def get_message(self, user): ...
    def get_icon(self, user, can_lock: bool = False): ...
    def get_locked_by(self, user, can_lock: bool = False): ...
    def get_description(self, user, can_lock: bool = False): ...
    def get_context_for_user(self, user, parent_context=None): ...

class ScheduledForPublishLock(BaseLock):
    def for_user(self, user): ...
    def get_message(self, user): ...
    def get_locked_by(self, user): ...
    def get_description(self, user): ...
