import types
from _typeshed import Incomplete
from wagtail import hooks as hooks
from wagtail.utils.registry import ObjectTypeRegistry as ObjectTypeRegistry

class LogFormatter:
    label: str
    message: str
    comment: str
    def format_message(self, log_entry): ...
    def format_comment(self, log_entry): ...

class LogContext:
    user: Incomplete
    uuid: Incomplete
    def __init__(self, user=None, generate_uuid: bool = True) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

empty_log_context: Incomplete

def activate(log_context) -> None: ...
def deactivate() -> None: ...
def get_active_log_context(): ...

class LogActionRegistry:
    has_scanned_for_actions: bool
    formatters: Incomplete
    choices: Incomplete
    log_entry_models_by_type: Incomplete
    log_entry_models: Incomplete
    def __init__(self) -> None: ...
    def scan_for_actions(self) -> None: ...
    def register_model(self, cls, log_entry_model) -> None: ...
    def register_action(self, action, *args): ...
    def get_choices(self): ...
    def get_formatter(self, log_entry): ...
    def action_exists(self, action): ...
    def get_log_entry_models(self): ...
    def get_action_label(self, action): ...
    def get_log_model_for_model(self, model): ...
    def get_log_model_for_instance(self, instance): ...
    def log(self, instance, action, user=None, uuid=None, **kwargs): ...
    def get_logs_for_instance(self, instance): ...

registry: Incomplete

def log(instance, action, **kwargs): ...
