import types
import uuid
from collections.abc import Callable
from typing import Any

from django.db.models import Model
from django.db.models.base import ModelBase

from wagtail.utils.registry import ObjectTypeRegistry

class LogFormatter:
    label: str
    message: str
    comment: str
    def format_message(self, log_entry: Any) -> str: ...
    def format_comment(self, log_entry: Any) -> str: ...

class LogContext:
    user: Any
    uuid: uuid.UUID | None
    def __init__(self, user: Any = None, generate_uuid: bool = True) -> None: ...
    def __enter__(self) -> LogContext: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

empty_log_context: LogContext

def activate(log_context: LogContext) -> None: ...
def deactivate() -> None: ...
def get_active_log_context() -> LogContext: ...

class LogActionRegistry:
    has_scanned_for_actions: bool
    formatters: dict[str, LogFormatter]
    choices: list[tuple[str, str]]
    log_entry_models_by_type: ObjectTypeRegistry
    log_entry_models: set[type[Model]]
    def __init__(self) -> None: ...
    def scan_for_actions(self) -> None: ...
    def register_model(self, cls: type, log_entry_model: type[Model]) -> None: ...
    def register_action(self, action: str, *args: str) -> Callable[[type[LogFormatter]], None] | None: ...
    def get_choices(self) -> list[tuple[str, str]]: ...
    def get_formatter(self, log_entry: Any) -> LogFormatter | None: ...
    def action_exists(self, action: str) -> bool: ...
    def get_log_entry_models(self) -> set[type[Model]]: ...
    def get_action_label(self, action: str) -> str: ...
    def get_log_model_for_model(self, model: type) -> type[Model] | None: ...
    def get_log_model_for_instance(self, instance: Any) -> type[Model] | None: ...
    def log(self, instance: Any, action: str, user: Any = None, uuid: uuid.UUID | None = None, **kwargs: Any) -> Any: ...
    def get_logs_for_instance(self, instance: Any) -> Any: ...

registry: LogActionRegistry

def log(instance: Any, action: str, **kwargs: Any) -> Any: ...
