from wagtail.permission_policies import ModelPermissionPolicy
from wagtail.permission_policies.collections import CollectionManagementPermissionPolicy
from wagtail.permission_policies.pages import PagePermissionPolicy

page_permission_policy: PagePermissionPolicy
site_permission_policy: ModelPermissionPolicy
collection_permission_policy: CollectionManagementPermissionPolicy
task_permission_policy: ModelPermissionPolicy
workflow_permission_policy: ModelPermissionPolicy
locale_permission_policy: ModelPermissionPolicy
