from django.db.models.query import ModelIterable
from treebeard.mp_tree import MP_NodeQuerySet
from wagtail.models.i18n import Locale as Locale
from wagtail.models.sites import Site as Site
from wagtail.search.queryset import SearchableQuerySetMixin as SearchableQuerySetMixin

class TreeQuerySet(MP_NodeQuerySet):
    def delete(self) -> None: ...
    def descendant_of_q(self, other, inclusive: bool = False): ...
    def descendant_of(self, other, inclusive: bool = False): ...
    def not_descendant_of(self, other, inclusive: bool = False): ...
    def child_of_q(self, other): ...
    def child_of(self, other): ...
    def not_child_of(self, other): ...
    def ancestor_of_q(self, other, inclusive: bool = False): ...
    def ancestor_of(self, other, inclusive: bool = False): ...
    def not_ancestor_of(self, other, inclusive: bool = False): ...
    def parent_of_q(self, other): ...
    def parent_of(self, other): ...
    def not_parent_of(self, other): ...
    def sibling_of_q(self, other, inclusive: bool = True): ...
    def sibling_of(self, other, inclusive: bool = True): ...
    def not_sibling_of(self, other, inclusive: bool = True): ...

class SpecificQuerySetMixin:
    def __init__(self, *args, **kwargs) -> None: ...
    def specific(self, defer: bool = False): ...
    @property
    def is_specific(self): ...
    def select_related(self, *fields, for_specific_subqueries: bool = False): ...
    def prefetch_related(self, *lookups, for_specific_subqueries: bool = False): ...

class PageQuerySet(SearchableQuerySetMixin, SpecificQuerySetMixin, TreeQuerySet):
    def live_q(self): ...
    def live(self): ...
    def not_live(self): ...
    def in_menu_q(self): ...
    def in_menu(self): ...
    def not_in_menu(self): ...
    def page_q(self, other): ...
    def page(self, other): ...
    def not_page(self, other): ...
    def type_q(self, *types): ...
    def type(self, *types): ...
    def not_type(self, *types): ...
    def exact_type_q(self, *types): ...
    def exact_type(self, *types): ...
    def not_exact_type(self, *types): ...
    def private_q(self): ...
    def public(self): ...
    def not_public(self): ...
    def private(self): ...
    def first_common_ancestor(self, include_self: bool = False, strict: bool = False): ...
    def unpublish(self) -> None: ...
    def defer_streamfields(self): ...
    def in_site(self, site): ...
    def translation_of_q(self, page, inclusive): ...
    def translation_of(self, page, inclusive: bool = False): ...
    def not_translation_of(self, page, inclusive: bool = False): ...
    def prefetch_workflow_states(self): ...
    def annotate_approved_schedule(self): ...
    def annotate_site_root_state(self): ...
    def annotate_has_untranslated_locale(self): ...

class SpecificIterable(ModelIterable):
    def __iter__(self): ...

class DeferredSpecificIterable(ModelIterable):
    def __iter__(self): ...
