from .tasks import update_reference_index_task as update_reference_index_task
from _typeshed import Incomplete
from collections.abc import Generator
from contextlib import contextmanager
from wagtail.models import Locale as Locale, Page as Page, ReferenceIndex as ReferenceIndex, Site as Site

logger: Incomplete

def post_save_site_signal_handler(instance, update_fields=None, **kwargs) -> None: ...
def post_delete_site_signal_handler(instance, **kwargs) -> None: ...
def pre_delete_page_unpublish(sender, instance, **kwargs) -> None: ...
def post_delete_page_log_deletion(sender, instance, **kwargs) -> None: ...
def reset_locales_display_names_cache(sender, instance, **kwargs) -> None: ...

reference_index_auto_update_disabled: Incomplete

@contextmanager
def disable_reference_index_auto_update() -> Generator[None]: ...
def update_reference_index_on_save(instance, **kwargs) -> None: ...
def remove_reference_index_on_delete(instance, **kwargs) -> None: ...
def connect_reference_index_signal_handlers_for_model(model) -> None: ...
def connect_reference_index_signal_handlers(**kwargs) -> None: ...
def disconnect_reference_index_signal_handlers_for_model(model) -> None: ...
def disconnect_reference_index_signal_handlers(**kwargs) -> None: ...
def register_signal_handlers() -> None: ...
