from wagtail.models import ReferenceIndex as ReferenceIndex

def update_reference_index_task(app_label, model_name, pk): ...
def delete_file_from_storage_task(deconstructed_storage, path) -> None: ...
