def update_reference_index_task(app_label: str, model_name: str, pk: str) -> None: ...
def delete_file_from_storage_task(deconstructed_storage: tuple[str, list[object], dict[str, object]], path: str) -> None: ...
