from wagtail import hooks as hooks
from wagtail.forms import PasswordViewRestrictionForm as PasswordViewRestrictionForm
from wagtail.models import Page as Page, PageViewRestriction as PageViewRestriction

def serve_chain(page, request, args, kwargs): ...
def serve(request, path): ...
def authenticate_with_password(request, page_view_restriction_id, page_id): ...
