from django.http import HttpRequest
from wagtail import hooks as hooks
from wagtail.compat import HTTPMethod as HTTPMethod
from wagtail.coreutils import get_content_languages as get_content_languages
from wagtail.log_actions import LogFormatter as LogFormatter
from wagtail.models import ModelLogEntry as ModelLogEntry, Page as Page, PageLogEntry as PageLogEntry, PageViewRestriction as PageViewRestriction
from wagtail.rich_text.pages import PageLinkHandler as PageLinkHandler
from wagtail.utils.timestamps import parse_datetime_localized as parse_datetime_localized, render_timestamp as render_timestamp

def require_wagtail_login(next): ...
def check_view_restrictions(callback): ...
def register_core_features(features) -> None: ...
def register_workflow_permissions(): ...
def register_task_permissions(): ...
def describe_collection_children(collection): ...
def register_core_log_actions(actions): ...
def register_workflow_log_actions(actions): ...
def check_request_method(page: Page, request: HttpRequest, *args, **kwargs): ...
