from _typeshed import Incomplete

ALLOWED_URL_SCHEMES: Incomplete
PROTOCOL_RE: Incomplete

def check_url(url_string): ...
def attribute_rule(allowed_attrs): ...

allow_without_attributes: Incomplete
DEFAULT_ELEMENT_RULES: Incomplete

class Whitelister:
    element_rules = DEFAULT_ELEMENT_RULES
    def clean(self, html): ...
    def clean_node(self, doc, node) -> None: ...
    def clean_string_node(self, doc, node) -> None: ...
    def clean_tag_node(self, doc, tag) -> None: ...
    def clean_unknown_node(self, doc, node) -> None: ...
