from _typeshed import Incomplete
from collections.abc import Generator

TASK_TYPES: Incomplete

def get_concrete_descendants(model_class, inclusive: bool = True) -> Generator[Incomplete, Incomplete]: ...
def get_task_types(task_class=None): ...
def publish_workflow_state(workflow_state, user=None) -> None: ...
