from wagtail.snippets.models import get_snippet_models as get_snippet_models

def get_permission_name(action, model): ...
def user_can_edit_snippet_type(user, model): ...
def user_can_access_snippets(user, models=None): ...
