from typing import Any

from django.db import models

class BaseCollectionManager(models.Manager["Collection"]): ...
class CollectionManager(BaseCollectionManager): ...

class Collection(models.Model):
    name: models.CharField[str, str]
    objects: CollectionManager  # type: ignore[assignment]
    def get_ancestors(self, inclusive: bool = False) -> models.QuerySet[Collection]: ...
    def get_descendants(self, inclusive: bool = False) -> models.QuerySet[Collection]: ...

class CollectionMember(models.Model):
    collection: models.ForeignKey[Collection, Collection]
    class Meta:
        abstract: bool

class CollectionViewRestriction(models.Model): ...
class GroupCollectionPermission(models.Model): ...
class GroupCollectionPermissionManager(models.Manager[GroupCollectionPermission]): ...
class UploadedFile(models.Model): ...

def get_root_collection_id() -> int: ...
