from typing import Any

from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.http import HttpRequest, HttpResponse
from treebeard.mp_tree import MP_Node

from wagtail.models.draft_state import DraftStateMixin
from wagtail.models.i18n import Locale, TranslatableMixin
from wagtail.models.locking import LockableMixin
from wagtail.models.preview import PreviewableMixin
from wagtail.models.revisions import RevisionMixin
from wagtail.models.specific import SpecificMixin
from wagtail.models.workflows import WorkflowMixin
from wagtail.query import PageQuerySet
from wagtail.search import index
from wagtail.url_routing import RouteResult

PAGE_TEMPLATE_VAR: str
COMMENTS_RELATION_NAME: str
PAGE_MODEL_CLASSES: list[type[Page]]
PAGE_PERMISSION_TYPES: list[tuple[str, str, str]]
PAGE_PERMISSION_TYPE_CHOICES: list[tuple[str, str]]
PAGE_PERMISSION_CODENAMES: list[str]

def get_page_models() -> list[type[Page]]: ...
def get_page_content_types(include_base_page_type: bool = True) -> models.QuerySet[ContentType]: ...
def get_streamfield_names(model_class: type[Page]) -> tuple[str, ...]: ...
def reassign_root_page_locale_on_delete(sender: type, instance: Locale, **kwargs: Any) -> None: ...

class BasePageManager(models.Manager[Any]):
    def get_queryset(self) -> PageQuerySet: ...
    def get_by_natural_key(self, url_path: str) -> Page: ...
    def first_common_ancestor_of(self, pages: list[Page], include_self: bool = False, strict: bool = False) -> Page: ...

PageManager = BasePageManager

class PageBase(models.base.ModelBase): ...

class AbstractPage(
    WorkflowMixin,
    PreviewableMixin,
    DraftStateMixin,
    LockableMixin,
    RevisionMixin,
    TranslatableMixin,
    SpecificMixin,
    MP_Node,
):
    objects: PageManager  # type: ignore[assignment]
    class Meta:
        abstract: bool

class Page(AbstractPage, index.Indexed, models.Model, metaclass=PageBase):
    title: models.CharField[str, str]
    draft_title: models.CharField[str, str]
    slug: models.SlugField[str, str]
    content_type: models.ForeignKey[ContentType, ContentType]
    url_path: models.TextField[str, str]
    owner: models.ForeignKey[Any, Any]
    seo_title: models.CharField[str, str]
    show_in_menus_default: bool
    show_in_menus: models.BooleanField[bool, bool]
    search_description: models.TextField[str, str]
    latest_revision_created_at: models.DateTimeField[Any, Any]
    alias_of: models.ForeignKey[Page | None, Page | None]
    search_fields: list[index.BaseField]
    is_creatable: bool
    max_count: int | None
    max_count_per_parent: int | None
    admin_default_ordering: str
    exclude_fields_in_copy: list[str]
    default_exclude_fields_in_copy: list[str]
    content_panels: list[Any]
    promote_panels: list[Any]
    settings_panels: list[Any]
    template: str
    ajax_template: str | None

    objects: PageManager  # type: ignore[assignment]

    @staticmethod
    def route_for_request(request: HttpRequest, path: str) -> RouteResult | None: ...
    @staticmethod
    def find_for_request(request: HttpRequest, path: str) -> Page | None: ...
    @classmethod
    def allowed_http_method_names(cls) -> list[str]: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    @property
    def revisions(self) -> Any: ...
    def get_base_content_type(self) -> ContentType: ...
    def get_content_type(self) -> ContentType: ...
    @classmethod
    def get_streamfield_names(cls) -> tuple[str, ...]: ...
    def set_url_path(self, parent: Page | None) -> str: ...
    def full_clean(self, *args: Any, **kwargs: Any) -> None: ...
    def clean(self) -> None: ...
    def is_site_root(self) -> bool: ...
    def save(self, clean: bool = True, user: Any | None = None, log_action: bool = False, **kwargs: Any) -> None: ...  # type: ignore[override]
    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]: ...
    @property
    def specific(self) -> Page: ...
    @property
    def specific_deferred(self) -> Page: ...
    @property
    def specific_class(self) -> type[Page] | None: ...
    def route(self, request: HttpRequest, path_components: list[str]) -> RouteResult: ...
    def serve(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context(self, request: HttpRequest, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def get_template(self, request: HttpRequest, *args: Any, **kwargs: Any) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def full_url(self) -> str: ...
    def get_url(self, request: HttpRequest | None = None, current_site: Any | None = None) -> str: ...
    def get_full_url(self, request: HttpRequest | None = None) -> str: ...
    def relative_url(self, current_site: Any, request: HttpRequest | None = None) -> str: ...
    def get_site(self) -> Any: ...
    def get_url_parts(self, request: HttpRequest | None = None) -> tuple[int, str, str] | None: ...
    def get_parent(self, *, update: bool = False) -> Page | None: ...
    def get_ancestors(self, inclusive: bool = False) -> PageQuerySet: ...
    def get_descendants(self, inclusive: bool = False) -> PageQuerySet: ...
    def get_siblings(self, inclusive: bool = True) -> PageQuerySet: ...
    def get_children(self) -> PageQuerySet: ...
    def has_unpublished_changes(self) -> bool: ...
    def get_verbose_name(self) -> str: ...
    @classmethod
    def get_verbose_name_plural(cls) -> str: ...
    def get_admin_display_title(self) -> str: ...
    @property
    def status_string(self) -> str: ...
    def get_latest_revision_as_object(self) -> Page: ...
    def unpublish(self, set_expired: bool = False, commit: bool = True, user: Any | None = None, log_action: bool = True) -> None: ...
    @property
    def localized(self) -> Page: ...
    class Meta:
        verbose_name: str
        verbose_name_plural: str

class Comment(models.Model): ...
class CommentReply(models.Model): ...
class GroupPagePermission(models.Model): ...
class GroupPagePermissionManager(models.Manager[GroupPagePermission]): ...
class PagePermissionTester: ...
class PageSubscription(models.Model): ...
class PageViewRestriction(models.Model): ...
class PageLogEntry(models.Model): ...
class PageLogEntryManager(models.Manager[PageLogEntry]): ...
class PageLogEntryQuerySet(models.QuerySet[PageLogEntry]): ...
class WorkflowPage(models.Model): ...
