from collections.abc import Iterable
from typing import Any, Self

from django.contrib.contenttypes.models import ContentType
from django.utils.functional import cached_property

class SpecificMixin:
    def get_specific(
        self,
        deferred: bool = False,
        copy_attrs: Iterable[str] | None = None,
        copy_attrs_exclude: Iterable[str] | None = None,
    ) -> Self: ...
    @cached_property
    def specific(self) -> Self: ...
    @cached_property
    def specific_deferred(self) -> Self: ...
    @cached_property
    def specific_class(self) -> type[Self] | None: ...
    @property
    def cached_content_type(self) -> ContentType: ...

class SpecificQuerySetMixin:
    _defer_streamfields: bool
    _specific_select_related_fields: tuple[str, ...]
    _specific_prefetch_related_lookups: tuple[str, ...]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def specific(self, defer: bool = False) -> Self: ...
    @property
    def is_specific(self) -> bool: ...
    def select_related(self, *fields: str, for_specific_subqueries: bool = False) -> Self: ...
    def prefetch_related(self, *lookups: str, for_specific_subqueries: bool = False) -> Self: ...
