from typing import Any

from django.db import models

class WorkflowMixin(models.Model):
    class Meta:
        abstract: bool

class AbstractWorkflow(models.Model):
    class Meta:
        abstract: bool

class Workflow(AbstractWorkflow): ...

class WorkflowManager(models.Manager[Workflow]): ...
class WorkflowContentType(models.Model): ...

class Task(models.Model): ...
class TaskManager(models.Manager[Task]): ...
class TaskQuerySet(models.QuerySet[Task]): ...

class TaskState(models.Model): ...
class TaskStateManager(models.Manager[TaskState]): ...
class BaseTaskStateManager(TaskStateManager): ...
class TaskStateQuerySet(models.QuerySet[TaskState]): ...

class WorkflowState(models.Model): ...
class WorkflowStateManager(models.Manager[WorkflowState]): ...
class WorkflowStateQuerySet(models.QuerySet[WorkflowState]): ...

class WorkflowTask(models.Model): ...

class AbstractGroupApprovalTask(Task):
    class Meta:
        abstract: bool

class GroupApprovalTask(AbstractGroupApprovalTask): ...
