from typing import Any

from django.db import models

class BaseField:
    field_name: str
    def __init__(self, field_name: str, **kwargs: Any) -> None: ...

class SearchField(BaseField):
    boost: float | None
    def __init__(self, field_name: str, boost: float | None = None, **kwargs: Any) -> None: ...

class AutocompleteField(BaseField):
    def __init__(self, field_name: str, **kwargs: Any) -> None: ...

class FilterField(BaseField):
    def __init__(self, field_name: str, **kwargs: Any) -> None: ...

class RelatedFields:
    field_name: str
    fields: list[BaseField]
    def __init__(self, field_name: str, fields: list[BaseField]) -> None: ...

class Indexed:
    search_fields: list[BaseField]
    @classmethod
    def get_search_fields(cls) -> list[BaseField]: ...

def class_is_indexed(cls: type) -> bool: ...
def get_indexed_models() -> list[type[models.Model]]: ...
def get_indexed_instance(instance: models.Model, check_exists: bool = True) -> models.Model | None: ...
def insert_or_update_object(instance: models.Model) -> None: ...
def remove_object(instance: models.Model) -> None: ...
