from typing import Any

class SearchQuery:
    def __and__(self, other: SearchQuery) -> And: ...
    def __or__(self, other: SearchQuery) -> Or: ...
    def __invert__(self) -> Not: ...

class PlainText(SearchQuery):
    def __init__(self, query_string: str, operator: str = ..., boost: float = 1.0) -> None: ...

class Phrase(SearchQuery):
    def __init__(self, query_string: str, boost: float = 1.0) -> None: ...

class Fuzzy(SearchQuery):
    def __init__(self, query_string: str, max_edits: int = 2, prefix_length: int = 0, boost: float = 1.0) -> None: ...

class Boost(SearchQuery):
    def __init__(self, subquery: SearchQuery, boost: float = 1.0) -> None: ...

class And(SearchQuery):
    def __init__(self, subqueries: list[SearchQuery]) -> None: ...

class Or(SearchQuery):
    def __init__(self, subqueries: list[SearchQuery]) -> None: ...

class Not(SearchQuery):
    def __init__(self, subquery: SearchQuery) -> None: ...

class MatchAll(SearchQuery): ...

MATCH_ALL: MatchAll
MATCH_NONE: SearchQuery
