from typing import Any

from django.db import models

def post_save_signal_handler(instance: models.Model, **kwargs: Any) -> None: ...
def post_delete_signal_handler(instance: models.Model, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
