from typing import Any

def post_save_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def post_delete_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
