from typing import Any

MAX_QUERY_STRING_LENGTH: int

def normalise_query_string(query_string: str) -> str: ...
def parse_query_string(query_string: str) -> tuple[Any, str]: ...
def separate_filters_from_query(query_string: str) -> tuple[dict[str, str], str]: ...
def get_search_fields(search_fields: list[Any]) -> list[Any]: ...
def get_descendants_content_types_pks(model: type) -> set[int]: ...
def get_ancestors_content_types_pks(model: type) -> set[int]: ...
def get_content_type_pk(model: type) -> int: ...
def get_descendant_models(model: type) -> list[type]: ...
def balanced_reduce(op: Any, seq: list[Any]) -> Any: ...
def deep_update(source: dict[str, Any], overrides: dict[str, Any]) -> dict[str, Any]: ...
