import re
from collections.abc import Iterator, Sequence
from functools import partial
from typing import Any

from django.http import QueryDict

from wagtail.search.index import SearchField
from wagtail.search.query import SearchQuery

MAX_QUERY_STRING_LENGTH: int
NOT_SET: object

OR: partial[Any]
AND: partial[Any]
ADD: partial[Any]
MUL: partial[Any]

filters_regexp: re.Pattern[str]

def normalise_query_string(query_string: str) -> str: ...
def parse_query_string(query_string: str) -> tuple[QueryDict, SearchQuery]: ...
def separate_filters_from_query(query_string: str) -> tuple[QueryDict, str]: ...
def get_search_fields(search_fields: list[Any]) -> Iterator[SearchField]: ...
def get_descendants_content_types_pks(model: type) -> list[int]: ...
def get_ancestors_content_types_pks(model: type) -> list[int]: ...
def get_content_type_pk(model: type) -> int: ...
def get_descendant_models(model: type) -> set[type]: ...
def balanced_reduce(op: Any, seq: Sequence[Any], initializer: Any = ...) -> Any: ...
def get_postgresql_connections() -> list[Any]: ...
