from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property
from wagtail import blocks as blocks
from wagtail.embeds.format import embed_to_frontend_html as embed_to_frontend_html

class EmbedValue:
    url: Incomplete
    max_width: Incomplete
    max_height: Incomplete
    def __init__(self, url, max_width=None, max_height=None) -> None: ...
    @cached_property
    def html(self): ...

class EmbedBlock(blocks.URLBlock):
    def get_default(self): ...
    def to_python(self, value): ...
    def get_prep_value(self, value): ...
    def value_for_form(self, value): ...
    def value_from_form(self, value): ...
    def clean(self, value): ...
    def normalize(self, value): ...
    class Meta:
        icon: str
