from django.utils.functional import cached_property as cached_property
from wagtail import blocks as blocks
from wagtail.embeds.format import embed_to_frontend_html as embed_to_frontend_html

class EmbedValue:
    url: str
    max_width: int | None
    max_height: int | None
    def __init__(self, url: str, max_width: int | None = None, max_height: int | None = None) -> None: ...
    @cached_property
    def html(self) -> str: ...
    def __str__(self) -> str: ...

class EmbedBlock(blocks.URLBlock):
    def get_default(self): ...
    def to_python(self, value): ...
    def get_prep_value(self, value): ...
    def value_for_form(self, value): ...
    def value_from_form(self, value): ...
    def clean(self, value): ...
    def normalize(self, value): ...
    class Meta:
        icon: str
