from .exceptions import EmbedUnsupportedProviderException as EmbedUnsupportedProviderException
from .finders import get_finders as get_finders
from .models import Embed as Embed
from wagtail.coreutils import accepts_kwarg as accepts_kwarg, safe_md5 as safe_md5

def get_finder_for_embed(url, max_width=None, max_height=None): ...
def get_embed(url, max_width=None, max_height=None): ...
def get_embed_hash(url, max_width=None, max_height=None): ...
