from wagtail.embeds import embeds as embeds
from wagtail.embeds.exceptions import EmbedException as EmbedException

def embed_to_frontend_html(url: str, max_width: int | None = None, max_height: int | None = None) -> str: ...
def embed_to_editor_html(url: str) -> str: ...
