from wagtail.embeds import embeds as embeds
from wagtail.embeds.exceptions import EmbedException as EmbedException

def embed_to_frontend_html(url, max_width=None, max_height=None): ...
def embed_to_editor_html(url): ...
