from _typeshed import Incomplete

animoto: Incomplete
audioboom: Incomplete
cacoo: Incomplete
chirb: Incomplete
circuitlab: Incomplete
clickthrough: Incomplete
clikthrough: Incomplete
collegehumor: Incomplete
coub: Incomplete
crowdsignal: Incomplete
crowd_ranking: Incomplete
dailymile: Incomplete
dailymotion: Incomplete
datastudio: Incomplete
deviantart: Incomplete
dipdive: Incomplete
dipity: Incomplete
dotsub: Incomplete
etsy: Incomplete
five_hundred_px: Incomplete
five_min: Incomplete
flickr: Incomplete
funny_or_die: Incomplete
geograph_gg: Incomplete
geograph_uk: Incomplete
github_gist: Incomplete
gmep: Incomplete
hlipp: Incomplete
huffduffer: Incomplete
hulu: Incomplete
ifixit: Incomplete
ifttt: Incomplete
iheart: Incomplete
issuu: Incomplete
justin_tv: Incomplete
kickstarter: Incomplete
kinomap: Incomplete
loom: Incomplete
major_league_gaming: Incomplete
meetup: Incomplete
minoto: Incomplete
mixcloud: Incomplete
mobypicture: Incomplete
nfb: Incomplete
official_fm: Incomplete
opera: Incomplete
photobucket: Incomplete
pinterest: Incomplete
reddit: Incomplete
roomshare: Incomplete
sapo: Incomplete
screenr: Incomplete
scribd: Incomplete
shoudio: Incomplete
sketchfab: Incomplete
skitch: Incomplete
slideshare: Incomplete
smugmug: Incomplete
soundcloud: Incomplete
speakerdeck: Incomplete
spotify: Incomplete
ted: Incomplete
tidal: Incomplete
tumblr: Incomplete
twenty_three_hq: Incomplete
twitter: Incomplete
urtak: Incomplete
ustream: Incomplete
videojug: Incomplete
viddler: Incomplete
vidyard: Incomplete
vimeo: Incomplete
vzaar: Incomplete
wistia: Incomplete
wordpress: Incomplete
yandex: Incomplete
yfrog: Incomplete
youtube: Incomplete
all_providers: Incomplete
