from typing import Any
from collections.abc import Iterable

from django.contrib.auth.models import AbstractBaseUser
from django.db.models import Model, QuerySet
from django.utils.functional import cached_property

class BasePermissionPolicy:
    permission_cache_name: str

    def __init__(self, model: type[Model] | str) -> None: ...
    @cached_property
    def model(self) -> type[Model]: ...
    def check_model(self, model: type[Model]) -> None: ...
    def get_all_permissions_for_user(self, user: AbstractBaseUser) -> set[Any]: ...
    def get_cached_permissions_for_user(self, user: AbstractBaseUser) -> set[Any]: ...
    def user_has_permission(self, user: AbstractBaseUser, action: str) -> bool: ...
    def user_has_any_permission(
        self, user: AbstractBaseUser, actions: Iterable[str]
    ) -> bool: ...
    def users_with_any_permission(
        self, actions: Iterable[str]
    ) -> QuerySet[AbstractBaseUser]: ...
    def users_with_permission(
        self, action: str
    ) -> QuerySet[AbstractBaseUser]: ...
    def user_has_permission_for_instance(
        self, user: AbstractBaseUser, action: str, instance: Model
    ) -> bool: ...
    def user_has_any_permission_for_instance(
        self, user: AbstractBaseUser, actions: Iterable[str], instance: Model
    ) -> bool: ...
    def instances_user_has_any_permission_for(
        self, user: AbstractBaseUser, actions: Iterable[str]
    ) -> QuerySet[Model]: ...
    def instances_user_has_permission_for(
        self, user: AbstractBaseUser, action: str
    ) -> QuerySet[Model]: ...
    def users_with_any_permission_for_instance(
        self, actions: Iterable[str], instance: Model
    ) -> QuerySet[AbstractBaseUser]: ...
    def users_with_permission_for_instance(
        self, action: str, instance: Model
    ) -> QuerySet[AbstractBaseUser]: ...

class BlanketPermissionPolicy(BasePermissionPolicy):
    def user_has_permission(self, user: AbstractBaseUser, action: str) -> bool: ...
    def user_has_any_permission(
        self, user: AbstractBaseUser, actions: Iterable[str]
    ) -> bool: ...
    def users_with_any_permission(
        self, actions: Iterable[str]
    ) -> QuerySet[AbstractBaseUser]: ...
    def users_with_permission(
        self, action: str
    ) -> QuerySet[AbstractBaseUser]: ...

class AuthenticationOnlyPermissionPolicy(BasePermissionPolicy):
    def user_has_permission(self, user: AbstractBaseUser, action: str) -> bool: ...
    def user_has_any_permission(
        self, user: AbstractBaseUser, actions: Iterable[str]
    ) -> bool: ...
    def users_with_any_permission(
        self, actions: Iterable[str]
    ) -> QuerySet[AbstractBaseUser]: ...
    def users_with_permission(
        self, action: str
    ) -> QuerySet[AbstractBaseUser]: ...

class BaseDjangoAuthPermissionPolicy(BasePermissionPolicy):
    def __init__(
        self, model: type[Model] | str, auth_model: type[Model] | str | None = None
    ) -> None: ...
    @cached_property
    def auth_model(self) -> type[Model]: ...
    @cached_property
    def app_label(self) -> str: ...
    @cached_property
    def model_name(self) -> str: ...

class ModelPermissionPolicy(BaseDjangoAuthPermissionPolicy):
    def user_has_permission(self, user: AbstractBaseUser, action: str) -> bool: ...
    def users_with_any_permission(
        self, actions: Iterable[str]
    ) -> QuerySet[AbstractBaseUser]: ...

class OwnershipPermissionPolicy(BaseDjangoAuthPermissionPolicy):
    owner_field_name: str

    def __init__(
        self,
        model: type[Model] | str,
        auth_model: type[Model] | str | None = None,
        owner_field_name: str = "owner",
    ) -> None: ...
    def check_model(self, model: type[Model]) -> None: ...
    def user_has_permission(self, user: AbstractBaseUser, action: str) -> bool: ...
    def users_with_any_permission(
        self, actions: Iterable[str]
    ) -> QuerySet[AbstractBaseUser]: ...
    def user_has_permission_for_instance(
        self, user: AbstractBaseUser, action: str, instance: Model
    ) -> bool: ...
    def user_has_any_permission_for_instance(
        self, user: AbstractBaseUser, actions: Iterable[str], instance: Model
    ) -> bool: ...
    def instances_user_has_any_permission_for(
        self, user: AbstractBaseUser, actions: Iterable[str]
    ) -> QuerySet[Model]: ...
    def users_with_any_permission_for_instance(
        self, actions: Iterable[str], instance: Model
    ) -> QuerySet[AbstractBaseUser]: ...
