from django.core.management.base import BaseCommand
from wagtail.models import PageLogEntry as PageLogEntry, Revision as Revision

def get_comparison(page, revision_a, revision_b): ...

class Command(BaseCommand):
    def handle(self, *args, **options) -> None: ...
    def log_page_action(self, action, revision, has_content_changes) -> None: ...
