from _typeshed import Incomplete
from django.core.management.base import BaseCommand
from wagtail.models import Collection as Collection, Page as Page

class Command(BaseCommand):
    help: str
    stealth_options: Incomplete
    def add_arguments(self, parser) -> None: ...
    def numberlist_to_string(self, numberlist): ...
    def handle(self, **options) -> None: ...
    def handle_model(self, model, model_name, model_name_plural, any_problems_fixed, options) -> None: ...
