from django.core.management.base import BaseCommand
from wagtail.models.pages import Page as Page

class Command(BaseCommand):
    def add_arguments(self, parser) -> None: ...
    def handle(self, *args, **options) -> None: ...
