from _typeshed import Incomplete
from collections.abc import Generator
from django.core.management.base import BaseCommand
from django.db import transaction
from wagtail.models import ReferenceIndex as ReferenceIndex
from wagtail.signal_handlers import disable_reference_index_auto_update as disable_reference_index_auto_update

DEFAULT_CHUNK_SIZE: int

class Command(BaseCommand):
    def write(self, *args, **kwargs) -> None: ...
    def add_arguments(self, parser) -> None: ...
    verbosity: Incomplete
    def handle(self, **options) -> None: ...
    def print_newline(self) -> None: ...
    def print_iter_progress(self, iterable) -> Generator[Incomplete]: ...
    @transaction.atomic
    def queryset_chunks(self, qs, chunk_size=...) -> Generator[Incomplete]: ...
