from _typeshed import Incomplete
from django.core.exceptions import ImproperlyConfigured

logger: Incomplete

class InvalidFrontendCacheBackendError(ImproperlyConfigured): ...

def get_backends(backend_settings=None, backends=None): ...
def purge_url_from_cache(url, backend_settings=None, backends=None) -> None: ...
def purge_urls_from_cache(urls, backend_settings=None, backends=None) -> None: ...
def purge_page_from_cache(page, backend_settings=None, backends=None, *, cache_object=None) -> None: ...
def purge_pages_from_cache(pages, backend_settings=None, backends=None, *, cache_object=None) -> None: ...

class PurgeBatch:
    urls: Incomplete
    cache_object: Incomplete
    def __init__(self, urls=None, *, cache_object=None) -> None: ...
    def add_url(self, url) -> None: ...
    def add_urls(self, urls) -> None: ...
    def add_page(self, page) -> None: ...
    def add_pages(self, pages) -> None: ...
    def purge(self, backend_settings=None, backends=None) -> None: ...
