from _typeshed import Incomplete
from django.forms.fields import ImageField
from wagtail.images.utils import get_accept_attributes as get_accept_attributes, get_allowed_image_extensions as get_allowed_image_extensions

def ImageFileExtensionValidator(value): ...

class WagtailImageField(ImageField):
    default_validators: Incomplete
    allowed_image_extensions: Incomplete
    max_upload_size: Incomplete
    max_image_pixels: Incomplete
    max_upload_size_text: Incomplete
    supported_formats_text: Incomplete
    help_text: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def check_image_file_format(self, f) -> None: ...
    def check_image_file_size(self, f) -> None: ...
    def check_image_pixel_size(self, f) -> None: ...
    def to_python(self, data): ...
    def widget_attrs(self, widget): ...
