from _typeshed import Incomplete
from wagtail.images.exceptions import InvalidFilterSpecError as InvalidFilterSpecError
from wagtail.images.rect import Rect as Rect, Vector as Vector
from wagtail.images.utils import parse_color_string as parse_color_string

class Operation:
    method: Incomplete
    args: Incomplete
    def __init__(self, method, *args) -> None: ...
    def construct(self, *args) -> None: ...

class ImageTransform:
    image_is_svg: Incomplete
    size: Incomplete
    scale: Incomplete
    offset: Incomplete
    def __init__(self, size, image_is_svg: bool = False) -> None: ...
    def clone(self): ...
    def resize(self, size): ...
    def crop(self, rect): ...
    def transform_vector(self, vector): ...
    def untransform_vector(self, vector): ...
    def get_rect(self): ...

class TransformOperation(Operation):
    def run(self, image, transform) -> None: ...

class FillOperation(TransformOperation):
    vary_fields: Incomplete
    width: Incomplete
    height: Incomplete
    crop_closeness: int
    def construct(self, size, *extra) -> None: ...
    def run(self, transform, image): ...

class MinMaxOperation(TransformOperation):
    width: Incomplete
    height: Incomplete
    def construct(self, size) -> None: ...
    def run(self, transform, image): ...

class WidthHeightOperation(TransformOperation):
    size: Incomplete
    def construct(self, size) -> None: ...
    def run(self, transform, image): ...

class ScaleOperation(TransformOperation):
    percent: Incomplete
    def construct(self, percent) -> None: ...
    def run(self, transform, image): ...

class FilterOperation(Operation):
    def run(self, willow, image, env) -> None: ...

class DoNothingOperation(FilterOperation):
    def construct(self) -> None: ...
    def run(self, willow, image, env): ...

class JPEGQualityOperation(FilterOperation):
    quality: Incomplete
    def construct(self, quality) -> None: ...
    def run(self, willow, image, env) -> None: ...

class AvifQualityOperation(FilterOperation):
    quality: Incomplete
    def construct(self, quality) -> None: ...
    def run(self, willow, image, env) -> None: ...

class WebPQualityOperation(FilterOperation):
    quality: Incomplete
    def construct(self, quality) -> None: ...
    def run(self, willow, image, env) -> None: ...

class FormatOperation(FilterOperation):
    supported_formats: Incomplete
    format: Incomplete
    options: Incomplete
    def construct(self, format, *options) -> None: ...
    def run(self, willow, image, env) -> None: ...

class BackgroundColorOperation(FilterOperation):
    color: Incomplete
    def construct(self, color_string) -> None: ...
    def run(self, willow, image, env): ...
