from _typeshed import Incomplete
from collections.abc import Generator, Iterable
from contextlib import contextmanager
from django.core.cache.backends.base import BaseCache
from django.core.files import File
from django.db import models
from django.utils.functional import cached_property as cached_property, classproperty
from io import BytesIO
from typing import Any, NamedTuple
from wagtail import hooks as hooks
from wagtail.coreutils import string_to_ascii as string_to_ascii
from wagtail.images.exceptions import InvalidFilterSpecError as InvalidFilterSpecError, UnknownOutputImageFormatError as UnknownOutputImageFormatError
from wagtail.images.image_operations import FilterOperation as FilterOperation, FormatOperation as FormatOperation, ImageTransform as ImageTransform, TransformOperation as TransformOperation
from wagtail.images.rect import Rect as Rect
from wagtail.images.utils import to_svg_safe_spec as to_svg_safe_spec
from wagtail.models import CollectionMember as CollectionMember, ReferenceIndex as ReferenceIndex
from wagtail.search import index as index
from wagtail.search.queryset import SearchableQuerySetMixin as SearchableQuerySetMixin
from wagtail.utils.file import hash_filelike as hash_filelike

logger: Incomplete
IMAGE_FORMAT_EXTENSIONS: Incomplete

class SourceImageIOError(IOError): ...

class ImageQuerySet(SearchableQuerySetMixin, models.QuerySet):
    def prefetch_renditions(self, *filters): ...

def get_upload_to(instance, filename): ...
def get_rendition_upload_to(instance, filename): ...
def get_rendition_storage(): ...

class ImageFileMixin:
    def is_stored_locally(self): ...
    file_size: Incomplete
    def get_file_size(self): ...
    @contextmanager
    def open_file(self) -> Generator[Incomplete]: ...
    @contextmanager
    def get_willow_image(self) -> Generator[Incomplete]: ...

class WagtailImageFieldFile(models.fields.files.ImageFieldFile):
    def get_image_dimensions(self): ...

class WagtailImageField(models.ImageField):
    attr_class = WagtailImageFieldFile

class AbstractImage(ImageFileMixin, CollectionMember, index.Indexed, models.Model):
    title: Incomplete
    file: Incomplete
    description: Incomplete
    width: Incomplete
    height: Incomplete
    created_at: Incomplete
    uploaded_by_user: Incomplete
    tags: Incomplete
    focal_point_x: Incomplete
    focal_point_y: Incomplete
    focal_point_width: Incomplete
    focal_point_height: Incomplete
    file_size: Incomplete
    file_hash: Incomplete
    objects: Incomplete
    decorative: bool
    contextual_alt_text: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_file_hash(self): ...
    def get_upload_to(self, filename): ...
    def get_usage(self): ...
    @property
    def usage_url(self): ...
    search_fields: Incomplete
    def __eq__(self, other): ...
    def __hash__(self): ...
    def get_rect(self): ...
    def get_focal_point(self): ...
    def has_focal_point(self): ...
    def set_focal_point(self, rect) -> None: ...
    def get_suggested_focal_point(self): ...
    @classmethod
    def get_rendition_model(cls): ...
    def clean_filter_for_svg(self, filter: Filter) -> Filter: ...
    def get_rendition(self, filter: Filter | str) -> AbstractRendition: ...
    def find_existing_rendition(self, filter: Filter) -> AbstractRendition: ...
    def create_rendition(self, filter: Filter) -> AbstractRendition: ...
    def get_renditions(self, *filters: Filter | str) -> dict[str, AbstractRendition]: ...
    def find_existing_renditions(self, *filters: Filter) -> dict[Filter, AbstractRendition]: ...
    def create_renditions(self, *filters: Filter) -> dict[Filter, AbstractRendition]: ...
    def generate_rendition_instance(self, filter: Filter, source: BytesIO) -> AbstractRendition: ...
    def generate_rendition_file(self, filter: Filter, *, source: File = None) -> File: ...
    def is_portrait(self): ...
    def is_landscape(self): ...
    def is_svg(self): ...
    @property
    def filename(self): ...
    @property
    def default_alt_text(self): ...
    def is_editable_by_user(self, user): ...
    class Meta:
        abstract: bool

class Image(AbstractImage):
    admin_form_fields: Incomplete
    class Meta(AbstractImage.Meta):
        verbose_name: Incomplete
        verbose_name_plural: Incomplete
        permissions: Incomplete

class Filter:
    spec_pattern: Incomplete
    pipe_spec_pattern: Incomplete
    expanding_spec_pattern: Incomplete
    pipe_expanding_spec_pattern: Incomplete
    spec: Incomplete
    def __init__(self, spec=None) -> None: ...
    @classmethod
    def expand_spec(self, spec: str | Iterable[str]) -> list[str]: ...
    @cached_property
    def operations(self): ...
    @property
    def transform_operations(self): ...
    @property
    def filter_operations(self): ...
    def get_transform(self, image, size=None): ...
    @contextmanager
    def get_willow_image(self, image: AbstractImage, source: File = None): ...
    def run(self, image: AbstractImage, output: BytesIO, source: File = None): ...
    def get_cache_key(self, image): ...
    def __eq__(self, value): ...
    def __hash__(self): ...

class ResponsiveImage:
    renditions: Incomplete
    attrs: Incomplete
    def __init__(self, renditions: dict[str, AbstractRendition], attrs: dict[str, Any] | None = None) -> None: ...
    @classmethod
    def get_width_srcset(cls, renditions_list: list[AbstractRendition]): ...
    def __html__(self): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: ResponsiveImage): ...

class FileFormat(NamedTuple):
    name: Incomplete
    mime_type: Incomplete

class Picture(ResponsiveImage):
    source_format_order: Incomplete
    formats: Incomplete
    def __init__(self, renditions: dict[str, AbstractRendition], attrs: dict[str, Any] | None = None) -> None: ...
    def get_formats(self, renditions: dict[str, AbstractRendition]) -> dict[str, list[AbstractRendition]]: ...
    def get_fallback_format(self): ...
    def __html__(self): ...

class AbstractRendition(ImageFileMixin, models.Model):
    filter_spec: Incomplete
    file: Incomplete
    width: Incomplete
    height: Incomplete
    focal_point_key: Incomplete
    wagtail_reference_index_ignore: bool
    @property
    def url(self): ...
    @property
    def alt(self): ...
    @property
    def attrs(self): ...
    @property
    def attrs_dict(self): ...
    @property
    def full_url(self): ...
    @property
    def filter(self): ...
    @cached_property
    def focal_point(self): ...
    @property
    def background_position_style(self): ...
    @property
    def background_position_x(self): ...
    @property
    def background_position_y(self): ...
    def img_tag(self, extra_attributes=None): ...
    def __html__(self): ...
    def get_upload_to(self, filename): ...
    @classmethod
    def check(cls, **kwargs): ...
    @staticmethod
    def construct_cache_key(image, filter_cache_key, filter_spec): ...
    @classproperty
    def cache_backend(cls) -> BaseCache: ...
    def get_cache_key(self): ...
    def purge_from_cache(self) -> None: ...
    class Meta:
        abstract: bool

class Rendition(AbstractRendition):
    image: Incomplete
    class Meta:
        unique_together: Incomplete
