from _typeshed import Incomplete

class Vector:
    x: Incomplete
    y: Incomplete
    def __init__(self, x, y) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __eq__(self, other): ...

class Rect:
    left: Incomplete
    top: Incomplete
    right: Incomplete
    bottom: Incomplete
    def __init__(self, left, top, right, bottom) -> None: ...
    size: Incomplete
    @property
    def width(self): ...
    @property
    def height(self): ...
    centroid: Incomplete
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def centroid_x(self): ...
    @property
    def centroid_y(self): ...
    def as_tuple(self): ...
    def clone(self): ...
    def round(self): ...
    def move_to_clamp(self, other): ...
    def move_to_cover(self, other): ...
    def transform(self, transform): ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __eq__(self, other): ...
    @classmethod
    def from_point(cls, x, y, width, height): ...
