def get_fill_filter_spec_migrations(app_name, rendition_model_name): ...
def parse_color_string(color_string): ...
def generate_signature(image_id, filter_spec, key=None): ...
def verify_signature(signature, image_id, filter_spec, key=None): ...
def find_image_duplicates(image, user, permission_policy): ...
def to_svg_safe_spec(filter_specs): ...
def get_allowed_image_extensions(): ...
def get_accept_attributes(): ...
