from wagtail.documents import get_document_model as get_document_model
from wagtail.tasks import delete_file_from_storage_task as delete_file_from_storage_task

def post_delete_file_cleanup(instance, **kwargs): ...
def register_signal_handlers() -> None: ...
