from _typeshed import Incomplete
from collections.abc import Generator, Mapping
from django.forms import MediaDefiningClass
from django.utils.functional import cached_property as cached_property
from wagtail.admin.ui.components import Component as Component
from wagtail.coreutils import get_locales_display_names as get_locales_display_names, multigetattr as multigetattr
from wagtail.models import Locale as Locale

class BaseColumn(metaclass=MediaDefiningClass):
    class Header:
        column: Incomplete
        def __init__(self, column) -> None: ...
        def render_html(self, parent_context): ...
    class Cell:
        column: Incomplete
        instance: Incomplete
        def __init__(self, column, instance) -> None: ...
        def render_html(self, parent_context): ...
    header_template_name: str
    cell_template_name: Incomplete
    name: Incomplete
    accessor: Incomplete
    label: Incomplete
    classname: Incomplete
    sort_key: Incomplete
    header: Incomplete
    width: Incomplete
    ascending_title_text: Incomplete
    descending_title_text: Incomplete
    def __init__(self, name, label=None, accessor=None, classname=None, sort_key=None, width=None, ascending_title_text=None, descending_title_text=None) -> None: ...
    def get_header_context_data(self, parent_context): ...
    @cached_property
    def header_template(self): ...
    @cached_property
    def cell_template(self): ...
    def render_header_html(self, parent_context): ...
    def get_cell_context_data(self, instance, parent_context): ...
    def render_cell_html(self, instance, parent_context): ...
    def get_cell(self, instance): ...

class Column(BaseColumn):
    cell_template_name: str
    empty_value_display: str
    def get_value(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class NumberColumn(Column):
    def get_cell_context_data(self, instance, parent_context): ...

class ButtonsColumnMixin:
    buttons: Incomplete
    def get_cell_context_data(self, instance, parent_context): ...
    def get_buttons(self, instance, parent_context): ...

class TitleColumn(Column):
    cell_template_name: str
    empty_value_display: Incomplete
    url_name: Incomplete
    label_prefix: Incomplete
    link_attrs: Incomplete
    link_classname: Incomplete
    id_accessor: Incomplete
    def __init__(self, name, url_name=None, get_url=None, get_title_id=None, label_prefix=None, get_label_id=None, link_classname=None, link_attrs=None, id_accessor: str = 'pk', **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...
    def get_link_attrs(self, instance, parent_context): ...
    def get_link_url(self, instance, parent_context): ...
    def get_title_id(self, instance, parent_context): ...
    def get_label_id(self, instance, parent_context): ...

class StatusFlagColumn(Column):
    cell_template_name: str
    true_label: Incomplete
    false_label: Incomplete
    def __init__(self, name, true_label=None, false_label=None, **kwargs) -> None: ...

class StatusTagColumn(Column):
    cell_template_name: str
    primary: Incomplete
    def __init__(self, name, primary=None, **kwargs) -> None: ...
    def get_primary(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class BooleanColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class LiveStatusTagColumn(StatusTagColumn):
    def __init__(self, **kwargs) -> None: ...

class LocaleColumn(Column):
    cell_template_name: str
    def __init__(self, **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...

class DateColumn(Column):
    cell_template_name: str

class UpdatedAtColumn(DateColumn):
    def __init__(self, **kwargs) -> None: ...

class UserColumn(Column):
    cell_template_name: str
    blank_display_name: Incomplete
    def __init__(self, name, blank_display_name: str = '', **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...

class BulkActionsCheckboxColumn(BaseColumn):
    header_template_name: str
    cell_template_name: str
    obj_type: Incomplete
    def __init__(self, *args, obj_type, **kwargs) -> None: ...
    def get_aria_describedby(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class UsageCountColumn(Column):
    cell_template_name: str

class ReferencesColumn(Column):
    cell_template_name: str
    describe_on_delete: Incomplete
    def __init__(self, name, label=None, accessor=None, classname=None, sort_key=None, width=None, get_url=None, describe_on_delete: bool = False) -> None: ...
    def get_edit_url(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class DownloadColumn(Column):
    cell_template_name: str
    def get_cell_context_data(self, instance, parent_context): ...

class RelatedObjectsColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class Table(Component):
    template_name: str
    classname: str
    header_row_classname: str
    ascending_title_text_format: Incomplete
    descending_title_text_format: Incomplete
    columns: Incomplete
    caption: Incomplete
    data: Incomplete
    base_url: Incomplete
    ordering: Incomplete
    base_attrs: Incomplete
    def __init__(self, columns, data, template_name=None, base_url=None, ordering=None, classname=None, attrs=None, caption=None) -> None: ...
    def get_caption(self): ...
    def get_context_data(self, parent_context): ...
    @property
    def media(self): ...
    @property
    def rows(self) -> Generator[Incomplete]: ...
    @property
    def row_count(self): ...
    @property
    def attrs(self): ...
    def get_row_classname(self, instance): ...
    def get_row_attrs(self, instance): ...
    def has_column_widths(self): ...
    def get_ascending_title_text(self, column): ...
    def get_descending_title_text(self, column): ...
    class Row(Mapping):
        table: Incomplete
        columns: Incomplete
        instance: Incomplete
        index: Incomplete
        def __init__(self, table, instance, index) -> None: ...
        def __len__(self) -> int: ...
        def __getitem__(self, key): ...
        def __iter__(self): ...
        @cached_property
        def classname(self): ...
        @cached_property
        def attrs(self): ...
