from collections import OrderedDict
from collections.abc import Callable, Generator, Mapping
from typing import Any

from django.forms import MediaDefiningClass
from django.utils.functional import cached_property as cached_property
from wagtail.admin.ui.components import Component as Component
from wagtail.coreutils import get_locales_display_names as get_locales_display_names, multigetattr as multigetattr
from wagtail.models import Locale as Locale

class BaseColumn(metaclass=MediaDefiningClass):
    class Header:
        column: BaseColumn
        def __init__(self, column) -> None: ...
        def render_html(self, parent_context): ...
    class Cell:
        column: BaseColumn
        instance: Any
        def __init__(self, column, instance) -> None: ...
        def render_html(self, parent_context): ...
    header_template_name: str
    cell_template_name: str | None
    name: str
    accessor: str | Callable[..., Any]
    label: str
    classname: str | None
    sort_key: str | None
    header: BaseColumn.Header
    width: str | None
    ascending_title_text: str | None
    descending_title_text: str | None
    def __init__(self, name, label=None, accessor=None, classname=None, sort_key=None, width=None, ascending_title_text=None, descending_title_text=None) -> None: ...
    def get_header_context_data(self, parent_context): ...
    @cached_property
    def header_template(self): ...
    @cached_property
    def cell_template(self): ...
    def render_header_html(self, parent_context): ...
    def get_cell_context_data(self, instance, parent_context): ...
    def render_cell_html(self, instance, parent_context): ...
    def get_cell(self, instance): ...

class Column(BaseColumn):
    cell_template_name: str
    empty_value_display: str
    def get_value(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class NumberColumn(Column):
    def get_cell_context_data(self, instance, parent_context): ...

class ButtonsColumnMixin:
    buttons: list[Any]
    def get_cell_context_data(self, instance, parent_context): ...
    def get_buttons(self, instance, parent_context): ...

class TitleColumn(Column):
    cell_template_name: str
    empty_value_display: str
    url_name: str | None
    label_prefix: str | None
    link_attrs: dict[str, Any]
    link_classname: str | None
    id_accessor: str
    def __init__(self, name, url_name=None, get_url=None, get_title_id=None, label_prefix=None, get_label_id=None, link_classname=None, link_attrs=None, id_accessor: str = 'pk', **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...
    def get_link_attrs(self, instance, parent_context): ...
    def get_link_url(self, instance, parent_context): ...
    def get_title_id(self, instance, parent_context): ...
    def get_label_id(self, instance, parent_context): ...

class StatusFlagColumn(Column):
    cell_template_name: str
    true_label: str | None
    false_label: str | None
    def __init__(self, name, true_label=None, false_label=None, **kwargs) -> None: ...

class StatusTagColumn(Column):
    cell_template_name: str
    primary: Any
    def __init__(self, name, primary=None, **kwargs) -> None: ...
    def get_primary(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class BooleanColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class LiveStatusTagColumn(StatusTagColumn):
    def __init__(self, **kwargs) -> None: ...

class LocaleColumn(Column):
    cell_template_name: str
    def __init__(self, **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...

class DateColumn(Column):
    cell_template_name: str

class UpdatedAtColumn(DateColumn):
    def __init__(self, **kwargs) -> None: ...

class UserColumn(Column):
    cell_template_name: str
    blank_display_name: str
    def __init__(self, name, blank_display_name: str = '', **kwargs) -> None: ...
    def get_cell_context_data(self, instance, parent_context): ...

class BulkActionsCheckboxColumn(BaseColumn):
    header_template_name: str
    cell_template_name: str
    obj_type: str
    def __init__(self, *args, obj_type, **kwargs) -> None: ...
    def get_aria_describedby(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class UsageCountColumn(Column):
    cell_template_name: str

class ReferencesColumn(Column):
    cell_template_name: str
    describe_on_delete: bool
    def __init__(self, name, label=None, accessor=None, classname=None, sort_key=None, width=None, get_url=None, describe_on_delete: bool = False) -> None: ...
    def get_edit_url(self, instance): ...
    def get_cell_context_data(self, instance, parent_context): ...

class DownloadColumn(Column):
    cell_template_name: str
    def get_cell_context_data(self, instance, parent_context): ...

class RelatedObjectsColumn(Column):
    cell_template_name: str
    def get_value(self, instance): ...

class Table(Component):
    template_name: str
    classname: str
    header_row_classname: str
    ascending_title_text_format: str
    descending_title_text_format: str
    columns: OrderedDict[str, BaseColumn]
    caption: str | None
    data: Any
    base_url: str | None
    ordering: str | None
    base_attrs: dict[str, Any]
    def __init__(self, columns, data, template_name=None, base_url=None, ordering=None, classname=None, attrs=None, caption=None) -> None: ...
    def get_caption(self): ...
    def get_context_data(self, parent_context): ...
    @property
    def media(self): ...
    @property
    def rows(self) -> Generator[Table.Row]: ...
    @property
    def row_count(self): ...
    @property
    def attrs(self): ...
    def get_row_classname(self, instance): ...
    def get_row_attrs(self, instance): ...
    def has_column_widths(self): ...
    def get_ascending_title_text(self, column): ...
    def get_descending_title_text(self, column): ...
    class Row(Mapping):
        table: Table
        columns: OrderedDict[str, BaseColumn]
        instance: Any
        index: int
        def __init__(self, table, instance, index) -> None: ...
        def __len__(self) -> int: ...
        def __getitem__(self, key): ...
        def __iter__(self): ...
        @cached_property
        def classname(self): ...
        @cached_property
        def attrs(self): ...
